// The standing catalogue: full programmes, not quick fixes.
//
// A quick order is something a government does by Friday. A programme is
// something it is still doing in three years, and the difference shows up in
// the price, the political capital and the length of the modifier it leaves
// behind.
//
// Every programme here declares, in `situational`, the circumstances that put
// it on the desk. Categories are pools, not menus: the economy tab of a country
// that is broke and stagnant offers different instruments from the economy tab
// of one that is rich and overheating, and neither offers all sixty.
//
// The rules for a programme:
//   · two political capital at the very least, usually three or four
//   · it changes the shape of the country, not just this quarter's numbers —
//     which in practice means it leaves a modifier that outlives your term
//   · it should read like a line in a budget speech
//   · nothing here duplicates a quick order; if it could be done in a fortnight
//     it belongs on the quick shelf

/** Defaults, so each programme below is only what makes it different. */
function p(id, name, category, blurb, opts = {}) {
  return {
    id,
    name,
    category,
    blurb,
    target: 'none',
    pc: 3,
    risk: 'medium',
    baseSuccess: 0.66,
    cost: { pctGdp: 1.2 },
    skills: [],
    ...opts,
  };
}

/** @type {Array<object>} */
export const PROGRAMMES = [
  // ══ Economy ═══════════════════════════════════════════════════════════════
  p('housing-programme', 'National Housing Programme', 'economy',
    'A million units on public land, built by anyone who will sign a fixed-price contract.',
    { situational: ['unrest', 'young', 'growing', 'stagnant'], cost: { pctGdp: 2.6 }, pc: 3,
      baseSuccess: 0.7, skills: [['stability', 0.14]],
      effects: {
        success: { self: { approval: 6, unrest: -6 },
          modifier: { label: 'Housing build-out', turns: 10, growth: 0.24 } },
        failure: { self: { approval: -4, unrest: 3 },
          modifier: { label: 'Stalled housing sites', turns: 5, growth: -0.12 } },
      } }),
  p('grid-modernisation', 'Grid Modernisation Programme', 'economy',
    'Transmission, storage, interconnectors. Nobody notices until the lights stay on.',
    { situational: ['accident', 'energy', 'techLag', 'growing'], cost: { pctGdp: 2.2 },
      skills: [['tech', 0.16], ['stability', 0.08]],
      effects: {
        success: { self: { tech: 3 }, modifier: { label: 'Modern grid', turns: 12, growth: 0.26 } },
        failure: { self: { unrest: 4, approval: -3 }, modifier: { label: 'Grid works overrunning', turns: 5, growth: -0.14 } },
      } }),
  p('deepwater-port', 'Deep-Water Port Expansion', 'economy',
    'Dredge, quay, cranes, rail spur. Trade follows draught.',
    { situational: ['maritime', 'exporter', 'growing'], cost: { pctGdp: 1.6 }, baseSuccess: 0.72,
      skills: [['tech', 0.1], ['influence', 0.08]],
      effects: {
        success: { self: { influence: 2 }, modifier: { label: 'Port capacity', turns: 12, growth: 0.3 } },
        failure: { self: { approval: -2 }, modifier: { label: 'Dredging overruns', turns: 4, growth: -0.1 } },
      } }),
  p('agricultural-reform', 'Agricultural Modernisation Act', 'economy',
    'Consolidation, irrigation, storage. The countryside will not thank you for any of it.',
    { situational: ['agrarian', 'famine', 'stagnant'], cost: { pctGdp: 1.4 }, risk: 'high',
      skills: [['stability', 0.14], ['tech', 0.1]],
      effects: {
        success: { self: { unrest: 3 }, modifier: { label: 'Farm modernisation', turns: 10, growth: 0.28 } },
        failure: { self: { unrest: 10, approval: -8 }, modifier: { label: 'Farmers’ revolt', turns: 5, growth: -0.16 } },
      } }),
  p('resource-nationalisation', 'Nationalise the Resource Sector', 'economy',
    'The ground belongs to the nation. So, from Monday, do the concessions.',
    { situational: ['resource', 'energy', 'debt', 'unpopular'], cost: { pctGdp: 0.8 }, pc: 5, risk: 'high',
      baseSuccess: 0.54, skills: [['stability', 0.18], ['influence', -0.1]],
      effects: {
        success: { self: { approval: 9, influence: -5, treasuryPctGdp: 3.5 },
          modifier: { label: 'State resource revenues', turns: 12, growth: 0.16, revenue: 0 },
          relationWithBlocs: { eu: -6, nato: -6 }, worldTension: 2 },
        failure: { self: { approval: -6, influence: -8, unrest: 6 },
          modifier: { label: 'Investment strike', turns: 8, growth: -0.4 } },
      } }),
  p('currency-defence', 'Defend the Currency', 'economy',
    'Reserves, rates, and a governor who will not blink first. One of you is wrong.',
    { situational: ['financial', 'inflation', 'debt'], cost: { pctGdp: 2.8 }, pc: 3, risk: 'high',
      baseSuccess: 0.58, skills: [['stability', 0.2], ['influence', 0.08]],
      effects: {
        success: { self: { stability: 5, approval: 3 }, modifier: { label: 'Currency stabilised', turns: 6, growth: 0.18 } },
        failure: { self: { stability: -8, approval: -8, unrest: 6 },
          modifier: { label: 'Reserves burned', turns: 6, growth: -0.5 } },
      } }),
  p('exchange-regime', 'Impose Capital Controls', 'economy',
    'Money stops leaving. So does money arriving, but that is next year’s problem.',
    { situational: ['financial', 'debt', 'sanctioned'], cost: { pctGdp: 0.3 }, pc: 4, risk: 'high',
      baseSuccess: 0.62, skills: [['stability', 0.16]],
      effects: {
        success: { self: { stability: 4, influence: -4 }, modifier: { label: 'Capital controls', turns: 8, growth: -0.12 } },
        failure: { self: { stability: -6, unrest: 7 }, modifier: { label: 'Black-market rate', turns: 6, growth: -0.35 } },
      } }),
  p('tax-reform', 'Comprehensive Tax Reform', 'economy',
    'Broaden the base, close the exemptions, and lose every friend you have in business.',
    { situational: ['debt', 'tight', 'stagnant'], cost: { pctGdp: 0.4 }, pc: 4, risk: 'high',
      baseSuccess: 0.58, skills: [['stability', 0.18], ['influence', 0.06]],
      effects: {
        success: { self: { approval: -4, treasuryPctGdp: 2.2 },
          modifier: { label: 'Broader tax base', turns: 14, growth: 0.12, revenue: 0 } },
        failure: { self: { approval: -9, unrest: 7 }, modifier: { label: 'Tax revolt', turns: 5, growth: -0.2 } },
      } }),
  p('wealth-tax', 'Levy on Great Fortunes', 'economy',
    'One per cent above a hundred million. It raises less than promised and costs more than expected.',
    { situational: ['debt', 'unrest', 'unpopular'], cost: { pctGdp: 0.2 }, pc: 4, risk: 'high',
      baseSuccess: 0.6, skills: [['stability', 0.14]],
      effects: {
        success: { self: { approval: 7, unrest: -5, treasuryPctGdp: 1.6 },
          modifier: { label: 'Capital flight', turns: 6, growth: -0.14 } },
        failure: { self: { approval: -3, treasuryPctGdp: 0.3 },
          modifier: { label: 'Capital flight', turns: 8, growth: -0.3 } },
      } }),
  p('export-credit', 'Export Credit Agency', 'economy',
    'Underwrite your own exporters against every risk a foreign buyer can invent.',
    { situational: ['exporter', 'stagnant', 'isolated'], cost: { pctGdp: 1 }, pc: 2, baseSuccess: 0.74,
      skills: [['influence', 0.12], ['tech', 0.06]],
      effects: {
        success: { self: { influence: 3 }, modifier: { label: 'Export finance', turns: 10, growth: 0.22 } },
        failure: { self: { treasuryPctGdp: -0.4 }, modifier: { label: 'Bad export book', turns: 5, growth: -0.08 } },
      } }),
  p('build-reserves', 'Build the Strategic Reserve', 'economy',
    'Grain, fuel, medicine, transformers. Cheap insurance until the quarter you need it.',
    { situational: ['commodityShock', 'famine', 'tension', 'energy', 'war'], cost: { pctGdp: 1.3 },
      pc: 2, baseSuccess: 0.78, skills: [['stability', 0.12]],
      effects: {
        success: { self: { stability: 4 }, modifier: { label: 'Strategic reserves', turns: 12, growth: 0.06, unrest: -0.4 } },
        failure: { self: { treasuryPctGdp: -0.5 } },
      } }),
  p('anti-corruption-drive', 'Anti-Corruption Commission', 'economy',
    'Independent, well-funded, and pointed at people who financed your campaign.',
    { situational: ['fragile', 'unpopular', 'stagnant', 'coup'], cost: { pctGdp: 0.5 }, pc: 4, risk: 'high',
      baseSuccess: 0.56, skills: [['stability', 0.2]],
      effects: {
        success: { self: { stability: 7, approval: 8, unrest: -4 },
          modifier: { label: 'Clean-hands drive', turns: 10, growth: 0.18 } },
        failure: { self: { stability: -7, approval: -5, unrest: 6 },
          modifier: { label: 'Backlash from the machine', turns: 6, growth: -0.15 } },
      } }),
  p('sovereign-bond', 'Issue a Sovereign Bond', 'economy',
    'Borrow long while somebody will still lend it. The coupon is the price of the delay.',
    { situational: ['debt', 'tight', 'war'], cost: { pctGdp: 0.1 }, pc: 2, baseSuccess: 0.72,
      skills: [['stability', 0.16], ['influence', 0.1]],
      effects: {
        success: { self: { treasuryPctGdp: 4.5 }, modifier: { label: 'Debt service', turns: 12, growth: -0.1 } },
        failure: { self: { stability: -4, treasuryPctGdp: 1.2 },
          modifier: { label: 'Failed auction', turns: 6, growth: -0.22 } },
      } }),
  p('rail-corridor', 'Continental Rail Corridor', 'economy',
    'A line to somewhere that matters, laid on somebody else’s ground with your money.',
    { situational: ['growing', 'influential', 'exporter', 'isolated'], cost: { pctGdp: 2.8 }, pc: 4,
      target: 'nation', baseSuccess: 0.62, skills: [['influence', 0.16], ['tech', 0.1]],
      effects: {
        success: { self: { influence: 5 }, relation: 16,
          modifier: { label: 'Corridor economics', turns: 14, growth: 0.3 },
          targetModifier: { label: 'Corridor economics', turns: 14, growth: 0.18 } },
        failure: { self: { approval: -3 }, relation: -4, modifier: { label: 'Corridor written down', turns: 6, growth: -0.18 } },
      } }),
  p('pension-overhaul', 'Raise the Retirement Age', 'economy',
    'Actuarially unavoidable and politically fatal. Choose which of those you mind more.',
    { situational: ['aging', 'debt', 'stagnant'], cost: { pctGdp: 0.2 }, pc: 5, risk: 'high',
      baseSuccess: 0.52, skills: [['stability', 0.2], ['approval', 0.1]],
      effects: {
        success: { self: { approval: -9, unrest: 6, treasuryPctGdp: 1.2 },
          modifier: { label: 'Pension savings', turns: 16, growth: 0.2 } },
        failure: { self: { approval: -14, unrest: 14, stability: -5 },
          modifier: { label: 'General strike', turns: 4, growth: -0.5 } },
      } }),
  p('immigration-programme', 'Managed Migration Programme', 'economy',
    'Fill the jobs nobody local will take, and own every consequence of saying so.',
    { situational: ['aging', 'stagnant', 'refugees', 'growing'], cost: { pctGdp: 0.6 }, pc: 4, risk: 'high',
      baseSuccess: 0.6, skills: [['stability', 0.16], ['approval', 0.08]],
      effects: {
        success: { self: { unrest: 4, approval: -3, population: 1.2 },
          modifier: { label: 'Labour supply', turns: 14, growth: 0.26 } },
        failure: { self: { unrest: 11, approval: -9, stability: -3 },
          modifier: { label: 'Migration backlash', turns: 6, growth: -0.1 } },
      } }),
  p('tourism-strategy', 'National Tourism Strategy', 'economy',
    'Visas, flights, and a campaign that will be mocked at home and work abroad.',
    { situational: ['peaceful', 'maritime', 'stagnant', 'calm'], cost: { pctGdp: 0.7 }, pc: 2,
      baseSuccess: 0.74, skills: [['influence', 0.14]],
      effects: {
        success: { self: { influence: 3, approval: 2 }, modifier: { label: 'Tourism boom', turns: 10, growth: 0.2 } },
        failure: { self: { approval: -2 } },
      } }),
  p('sanctions-workaround', 'Build the Workaround', 'economy',
    'Shadow banking, re-flagged tankers, and intermediaries in three friendly jurisdictions.',
    { situational: ['sanctioned', 'pariah', 'isolated'], cost: { pctGdp: 1.4 }, pc: 4, risk: 'high',
      covert: true, baseSuccess: 0.58, skills: [['influence', 0.14], ['tech', 0.1]],
      effects: {
        success: { self: { influence: 2 }, modifier: { label: 'Sanctions workaround', turns: 10, growth: 0.34 } },
        failure: { self: { influence: -6, approval: -3 },
          modifier: { label: 'Secondary sanctions', turns: 8, growth: -0.35 } },
      } }),
  p('reconstruction-fund', 'National Reconstruction Fund', 'economy',
    'Rebuild what the last quarter took down, and put the bill on the next decade.',
    { situational: ['disaster', 'accident', 'war', 'occupied', 'conquest'], cost: { pctGdp: 2.4 }, pc: 3,
      baseSuccess: 0.72, skills: [['stability', 0.16]],
      effects: {
        success: { self: { approval: 7, unrest: -7, stability: 4 },
          modifier: { label: 'Reconstruction', turns: 10, growth: 0.24 } },
        failure: { self: { approval: -5, unrest: 5 }, modifier: { label: 'Reconstruction stalled', turns: 5, growth: -0.12 } },
      } }),

  // ══ Military ══════════════════════════════════════════════════════════════
  p('air-defence-network', 'Integrated Air Defence Network', 'military',
    'Layered radar and interceptors over everything you cannot afford to lose.',
    { situational: ['war', 'tension', 'hostileNeighbour', 'escalation', 'attack'], cost: { pctGdp: 2.2 },
      pc: 3, baseSuccess: 0.7, skills: [['tech', 0.18], ['military', 0.08]],
      effects: {
        success: { self: { military: 4, readiness: 5, tech: 2 },
          modifier: { label: 'Integrated air defence', turns: 12, readiness: 0.3 } },
        failure: { self: { treasuryPctGdp: -0.6, approval: -3 } },
      } }),
  p('blue-water-navy', 'Blue-Water Fleet Programme', 'military',
    'Hulls that can stay at sea for six months. Everything else is a coastguard.',
    { situational: ['maritime', 'strongArmy', 'rich', 'tension'], cost: { pctGdp: 3.2 }, pc: 4,
      baseSuccess: 0.64, skills: [['tech', 0.14], ['military', 0.12]],
      effects: {
        success: { self: { military: 7, influence: 5 },
          modifier: { label: 'Fleet expansion', turns: 16, growth: -0.12, readiness: 0.2 }, worldTension: 3 },
        failure: { self: { approval: -4 }, modifier: { label: 'Shipyard overruns', turns: 8, growth: -0.3 } },
      } }),
  p('drone-force', 'Stand Up a Drone Command', 'military',
    'Cheap, attritable, and the only line item where you get more war for less money.',
    { situational: ['war', 'weakArmy', 'techLead', 'tight', 'hollowArmy'], cost: { pctGdp: 0.9 }, pc: 2,
      baseSuccess: 0.74, skills: [['tech', 0.2]],
      effects: {
        success: { self: { military: 5, readiness: 6, tech: 2 },
          modifier: { label: 'Drone command', turns: 10, readiness: 0.35 } },
        failure: { self: { readiness: -2, approval: -2 } },
      } }),
  p('nco-corps', 'Professionalise the NCO Corps', 'military',
    'Pay, schools, careers. It is the least visible defence spending and the best value.',
    { situational: ['hollowArmy', 'weakArmy', 'war', 'coup'], cost: { pctGdp: 0.8 }, pc: 2,
      baseSuccess: 0.78, skills: [['stability', 0.12], ['tech', 0.06]],
      effects: {
        success: { self: { readiness: 9, military: 2, stability: 2 },
          modifier: { label: 'Professional cadre', turns: 14, readiness: 0.4 } },
        failure: { self: { readiness: 1, approval: -2 } },
      } }),
  p('munitions-industry', 'Munitions Industrial Base', 'military',
    'Shell lines, propellant, and the ammonia plant nobody thought was strategic.',
    { situational: ['war', 'warStalled', 'tension', 'casualties', 'exporter'], cost: { pctGdp: 1.8 }, pc: 3,
      baseSuccess: 0.7, skills: [['tech', 0.12], ['military', 0.08]],
      effects: {
        success: { self: { military: 4, readiness: 6 },
          modifier: { label: 'Munitions capacity', turns: 14, readiness: 0.5, growth: 0.08 } },
        failure: { self: { treasuryPctGdp: -0.5 }, modifier: { label: 'Empty magazines', turns: 6, readiness: -0.3 } },
      } }),
  p('conscription-reform', 'Restructure Conscription', 'military',
    'Shorter service, harder training, and a reserve that could actually be called.',
    { situational: ['hollowArmy', 'war', 'young', 'weakArmy'], cost: { pctGdp: 0.7 }, pc: 4, risk: 'high',
      baseSuccess: 0.62, skills: [['stability', 0.16]],
      effects: {
        success: { self: { readiness: 10, military: 3, unrest: 5, approval: -4 } },
        failure: { self: { unrest: 12, approval: -10, readiness: 2, stability: -3 } },
      } }),
  p('base-network', 'Overseas Basing Agreement', 'military',
    'Fuel, runway, and a status-of-forces annex nobody in their parliament has read.',
    { situational: ['influential', 'strongArmy', 'tension', 'maritime'], cost: { pctGdp: 1.2 }, pc: 4,
      target: 'nation', baseSuccess: 0.56, risk: 'high', skills: [['influence', 0.2], ['military', 0.08]],
      effects: {
        success: { self: { influence: 6, military: 3, readiness: 3 }, relation: 10,
          modifier: { label: 'Forward basing', turns: 14, readiness: 0.3 }, worldTension: 4 },
        failure: { self: { influence: -4 }, relation: -14, worldTension: 2 },
      } }),
  p('missile-programme', 'Long-Range Strike Programme', 'military',
    'Reach past the border without crossing it. Everyone within range will notice.',
    { situational: ['tension', 'hostileNeighbour', 'war', 'strongArmy', 'techLead'], cost: { pctGdp: 2 },
      pc: 4, risk: 'high', baseSuccess: 0.64, skills: [['tech', 0.2], ['military', 0.08]],
      effects: {
        success: { self: { military: 7, tech: 3 }, worldTension: 6,
          modifier: { label: 'Deep-strike capability', turns: 14, readiness: 0.25 } },
        failure: { self: { military: 1, approval: -4 }, worldTension: 3 },
      } }),
  p('veterans-settlement', 'Veterans’ Settlement', 'military',
    'Pensions, land, hospitals. Armies that come home unpaid do not stay home.',
    { situational: ['casualties', 'warExhausted', 'coup', 'war', 'peace'], cost: { pctGdp: 1.1 }, pc: 2,
      baseSuccess: 0.78, skills: [['stability', 0.16], ['approval', 0.08]],
      effects: {
        success: { self: { stability: 6, approval: 6, unrest: -6 },
          modifier: { label: 'Veterans’ settlement', turns: 10, unrest: -0.4 } },
        failure: { self: { unrest: 7, stability: -5, approval: -5 } },
      } }),
  p('coup-proofing', 'Restructure the Officer Corps', 'military',
    'Rotate the commands, split the garrisons, promote the loyal. Everybody understands why.',
    { situational: ['coup', 'fragile', 'boiling', 'warLosing'], cost: { pctGdp: 0.5 }, pc: 4, risk: 'high',
      baseSuccess: 0.6, skills: [['stability', 0.2], ['influence', 0.06]],
      effects: {
        success: { self: { stability: 9, readiness: -4 },
          modifier: { label: 'Loyalist command', turns: 12, readiness: -0.3 } },
        failure: { self: { stability: -10, readiness: -6, unrest: 8 } },
      } }),
  p('joint-command', 'Create a Joint Command', 'military',
    'One headquarters, one plan, and three services who would rather not.',
    { situational: ['warStalled', 'warLosing', 'hollowArmy', 'peace'], cost: { pctGdp: 0.4 }, pc: 3,
      baseSuccess: 0.68, skills: [['tech', 0.12], ['stability', 0.1]],
      effects: {
        success: { self: { readiness: 8, military: 2 }, modifier: { label: 'Joint command', turns: 12, readiness: 0.35 } },
        failure: { self: { readiness: -3, stability: -2 } },
      } }),
  p('border-fortification', 'Fortify the Frontier', 'military',
    'Ditches, minefields, sensors and concrete along the ground you intend to keep.',
    { situational: ['hostileNeighbour', 'borderChange', 'warNextDoor', 'war', 'feared'], cost: { pctGdp: 1.5 },
      pc: 3, baseSuccess: 0.74, skills: [['military', 0.1], ['stability', 0.08]],
      effects: {
        success: { self: { military: 3, readiness: 4, stability: 3 },
          modifier: { label: 'Fortified frontier', turns: 14, readiness: 0.25 }, worldTension: 2 },
        failure: { self: { treasuryPctGdp: -0.6 }, worldTension: 1 },
      } }),
  p('sealift', 'Strategic Lift Command', 'military',
    'Ships and aircraft whose only job is moving your army to where the war is.',
    { situational: ['war', 'occupier', 'influential', 'maritime'], cost: { pctGdp: 1.3 }, pc: 3,
      baseSuccess: 0.7, skills: [['tech', 0.12], ['military', 0.08]],
      effects: {
        success: { self: { readiness: 8, military: 2 }, modifier: { label: 'Strategic lift', turns: 12, readiness: 0.3 } },
        failure: { self: { readiness: -2 } },
      } }),
  p('arms-export-drive', 'Arms Export Offensive', 'military',
    'Sell what you build to anyone the lawyers can clear, and some they cannot.',
    { situational: ['strongArmy', 'exporter', 'debt', 'tension'], cost: { pctGdp: 0.4 }, pc: 3, risk: 'high',
      baseSuccess: 0.66, skills: [['influence', 0.14], ['military', 0.1]],
      effects: {
        success: { self: { treasuryPctGdp: 2, influence: 4 },
          modifier: { label: 'Arms export book', turns: 12, growth: 0.16 }, worldTension: 3 },
        failure: { self: { influence: -5, approval: -3 }, worldTension: 2 },
      } }),
  p('demobilise', 'Demobilisation Programme', 'military',
    'Send them home, cut the establishment, and hope you never want it back.',
    { situational: ['peace', 'debt', 'warExhausted', 'calm'], cost: { pctGdp: 0.3 }, pc: 3,
      baseSuccess: 0.72, skills: [['stability', 0.14]],
      effects: {
        success: { self: { military: -4, readiness: -5, approval: 5, treasuryPctGdp: 1.4 },
          modifier: { label: 'Peace dividend', turns: 12, growth: 0.28 } },
        failure: { self: { unrest: 8, stability: -4, military: -3 } },
      } }),

  // ══ Diplomacy ═════════════════════════════════════════════════════════════
  p('summit-host', 'Host the Summit', 'diplomacy',
    'Two days, forty delegations, and a communiqué drafted before anyone arrives.',
    { situational: ['tension', 'influential', 'isolated', 'war', 'brink'], cost: { pctGdp: 0.5 }, pc: 3,
      baseSuccess: 0.7, skills: [['influence', 0.22]],
      effects: {
        success: { self: { influence: 7, approval: 3 }, worldTension: -5,
          modifier: { label: 'Convening power', turns: 8, influence: 0.3 } },
        failure: { self: { influence: -4, approval: -3 }, worldTension: 1 },
      } }),
  p('security-guarantee', 'Extend a Security Guarantee', 'diplomacy',
    'Say out loud that an attack on them is an attack on you, and mean it.',
    { situational: ['warNextDoor', 'neighbourCrisis', 'hostileNeighbour', 'influential', 'strongArmy'],
      cost: { pctGdp: 0.3 }, pc: 5, target: 'nation', risk: 'high', baseSuccess: 0.62,
      skills: [['influence', 0.18], ['military', 0.1]],
      effects: {
        success: { self: { influence: 6 }, relation: 30, worldTension: 4,
          modifier: { label: 'Guarantee obligations', turns: 16, readiness: -0.1 } },
        failure: { self: { influence: -6, approval: -4 }, relation: 6, worldTension: 3 },
      } }),
  p('recognition-campaign', 'Campaign for Their Recognition', 'diplomacy',
    'Spend your own standing getting a seat, a flag and a bank account for somebody else.',
    { situational: ['newState', 'conquest', 'borderChange'], cost: { pctGdp: 0.4 }, pc: 4,
      target: 'nation', risk: 'high', baseSuccess: 0.58, skills: [['influence', 0.24]],
      effects: {
        success: { self: { influence: 5 }, relation: 38, target: { influence: 8, stability: 4 },
          worldTension: 4 },
        failure: { self: { influence: -6, approval: -3 }, relation: 8, worldTension: 2 },
      } }),
  p('debt-forgiveness', 'Forgive the Debt', 'diplomacy',
    'Write off what they were never going to pay, and buy a generation of goodwill.',
    { situational: ['rich', 'influential', 'refugees', 'neighbourCrisis'], cost: { pctGdp: 1.6 }, pc: 3,
      target: 'nation', baseSuccess: 0.8, skills: [['influence', 0.16]],
      effects: {
        success: { self: { influence: 6, approval: -2 }, relation: 32, target: { stability: 5 },
          targetModifier: { label: 'Debt relief', turns: 10, growth: 0.2 } },
        failure: { self: { approval: -4 }, relation: 12 },
      } }),
  p('normalise-relations', 'Normalise Relations', 'diplomacy',
    'Embassies reopen, the old file is sealed, and both sides pretend it was mutual.',
    { situational: ['hostileNeighbour', 'sanctioned', 'peace', 'escalation', 'isolated'],
      cost: { pctGdp: 0.2 }, pc: 4, target: 'nation', baseSuccess: 0.58, relationFloor: -70,
      skills: [['influence', 0.24]],
      effects: {
        success: { self: { influence: 5, approval: 2 }, relation: 40, worldTension: -4 },
        failure: { self: { approval: -3 }, relation: -6 },
      } }),
  p('cultural-programme', 'Global Cultural Programme', 'diplomacy',
    'Institutes, scholarships, a film fund. Slow, cheap, and it outlasts every government.',
    { situational: ['isolated', 'pariah', 'feared', 'peaceful', 'rich'], cost: { pctGdp: 0.5 }, pc: 2,
      baseSuccess: 0.8, skills: [['influence', 0.16]],
      effects: {
        success: { self: { influence: 5 }, modifier: { label: 'Cultural reach', turns: 14, influence: 0.35 } },
        failure: { self: { influence: 1, approval: -1 } },
      } }),
  p('diaspora-strategy', 'Diaspora Engagement Strategy', 'diplomacy',
    'Votes, remittances and lobbying, from people whose passports you renewed.',
    { situational: ['refugees', 'isolated', 'stagnant', 'debt'], cost: { pctGdp: 0.3 }, pc: 2,
      baseSuccess: 0.76, skills: [['influence', 0.14]],
      effects: {
        success: { self: { influence: 4, treasuryPctGdp: 0.6 },
          modifier: { label: 'Remittance inflows', turns: 12, growth: 0.16 } },
        failure: { self: { influence: -1 } },
      } }),
  p('climate-accord', 'Lead a Climate Accord', 'diplomacy',
    'Targets you can hit, verification you can live with, and a headline everyone can claim.',
    { situational: ['disaster', 'influential', 'peaceful', 'techLead'], cost: { pctGdp: 0.8 }, pc: 3,
      baseSuccess: 0.66, skills: [['influence', 0.2], ['tech', 0.08]],
      effects: {
        success: { self: { influence: 6, approval: 3 }, worldTension: -4,
          modifier: { label: 'Accord obligations', turns: 12, growth: -0.06, tech: 0.2 } },
        failure: { self: { influence: -3, approval: -3 } },
      } }),
  p('arms-control', 'Open Arms-Control Talks', 'diplomacy',
    'Ceilings, inspections, and a verification annex three times the length of the treaty.',
    { situational: ['escalation', 'brink', 'nuclear', 'nuclearUsed', 'tension'], cost: { pctGdp: 0.3 },
      pc: 4, target: 'nation', baseSuccess: 0.56, skills: [['influence', 0.22], ['tech', 0.06]],
      effects: {
        success: { self: { influence: 6, approval: 4 }, relation: 22, worldTension: -8 },
        failure: { self: { influence: -3 }, relation: -4, worldTension: 2 },
      } }),
  p('war-crimes-referral', 'Refer It to the Court', 'diplomacy',
    'File the case, publish the evidence, and accept that enforcement is somebody else’s problem.',
    { situational: ['conquest', 'nuclearUsed', 'casualties', 'attack', 'pariah'], cost: { pctGdp: 0.1 },
      pc: 3, target: 'nation', risk: 'high', baseSuccess: 0.64, skills: [['influence', 0.2]],
      effects: {
        success: { self: { influence: 5, approval: 4 }, relation: -22, target: { influence: -8, stability: -3 },
          worldTension: 3 },
        failure: { self: { influence: -4 }, relation: -14, worldTension: 2 },
      } }),
  p('refugee-compact', 'Regional Refugee Compact', 'diplomacy',
    'Quotas, money and a processing centre nobody wants in their constituency.',
    { situational: ['refugees', 'neighbourCrisis', 'warNextDoor', 'famine'], cost: { pctGdp: 1 }, pc: 3,
      baseSuccess: 0.68, skills: [['influence', 0.18], ['stability', 0.08]],
      effects: {
        success: { self: { influence: 5, unrest: 3, approval: -2 }, worldTension: -3,
          modifier: { label: 'Refugee compact', turns: 10, growth: 0.06, unrest: 0.2 } },
        failure: { self: { unrest: 8, approval: -6, influence: -2 } },
      } }),
  p('mineral-partnership', 'Strategic Minerals Partnership', 'diplomacy',
    'Their ground, your smelters, and an offtake agreement running twenty years.',
    { situational: ['resource', 'techLag', 'exporter', 'growing'], cost: { pctGdp: 1.1 }, pc: 3,
      target: 'nation', baseSuccess: 0.66, skills: [['influence', 0.16], ['tech', 0.08]],
      effects: {
        success: { self: { influence: 4, tech: 2 }, relation: 18,
          modifier: { label: 'Minerals offtake', turns: 14, growth: 0.24 },
          targetModifier: { label: 'Minerals offtake', turns: 14, growth: 0.16 } },
        failure: { self: { influence: -2 }, relation: -4 },
      } }),
  p('freedom-of-navigation', 'Freedom of Navigation Programme', 'diplomacy',
    'Sail where the law says you may and they say you may not. Repeatedly.',
    { situational: ['maritime', 'tension', 'hostileNeighbour', 'strongArmy'], cost: { pctGdp: 0.6 },
      pc: 3, target: 'nation', risk: 'high', baseSuccess: 0.66, skills: [['military', 0.14], ['influence', 0.08]],
      effects: {
        success: { self: { influence: 5, military: 1 }, relation: -14, worldTension: 5 },
        failure: { self: { influence: -4, readiness: -2 }, relation: -22, worldTension: 8 },
      } }),
  p('armed-neutrality', 'Declare Armed Neutrality', 'diplomacy',
    'Out of everyone’s war, in nobody’s pocket, and armed enough to be taken seriously.',
    { situational: ['warNextDoor', 'tension', 'feared', 'escalation'], cost: { pctGdp: 0.6 }, pc: 5,
      risk: 'high', baseSuccess: 0.6, skills: [['influence', 0.12], ['stability', 0.12]],
      effects: {
        success: { self: { influence: -3, stability: 6, approval: 6, readiness: 3 }, worldTension: -4,
          modifier: { label: 'Armed neutrality', turns: 14, growth: 0.1, readiness: 0.15 } },
        failure: { self: { influence: -8, approval: -5, stability: -3 } },
      } }),
  p('development-bank', 'Found a Development Bank', 'diplomacy',
    'Lend on your terms, in your currency, to countries the incumbents priced out.',
    { situational: ['rich', 'influential', 'growing', 'isolated'], cost: { pctGdp: 2.2 }, pc: 4,
      baseSuccess: 0.66, skills: [['influence', 0.2], ['stability', 0.08]],
      effects: {
        success: { self: { influence: 9 }, modifier: { label: 'Development lending', turns: 16, influence: 0.4, growth: 0.08 } },
        failure: { self: { influence: -3, treasuryPctGdp: -0.8 } },
      } }),
  p('hostage-diplomacy', 'Negotiate the Prisoner Exchange', 'diplomacy',
    'A list each, a plane each, and a press conference neither side controls.',
    { situational: ['hostileNeighbour', 'attack', 'escalation', 'war'], cost: { pctGdp: 0.1 }, pc: 3,
      target: 'nation', baseSuccess: 0.62, skills: [['influence', 0.2]],
      effects: {
        success: { self: { approval: 8, influence: 3 }, relation: 18, worldTension: -3 },
        failure: { self: { approval: -6, influence: -3 }, relation: -8 },
      } }),

  // ══ Domestic ══════════════════════════════════════════════════════════════
  p('constitutional-reform', 'Constitutional Reform', 'domestic',
    'Rewrite the rules of the game while standing on the board.',
    { situational: ['fragile', 'coup', 'unpopular', 'newState', 'boiling'], cost: { pctGdp: 0.5 }, pc: 5,
      risk: 'high', baseSuccess: 0.54, skills: [['stability', 0.22], ['influence', 0.06]],
      effects: {
        success: { self: { stability: 12, approval: 5, unrest: -6 },
          modifier: { label: 'New constitutional order', turns: 16, unrest: -0.3 } },
        failure: { self: { stability: -10, unrest: 12, approval: -8 } },
      } }),
  p('healthcare-programme', 'Universal Health Programme', 'domestic',
    'Coverage for everyone, costing rather more than the model said it would.',
    { situational: ['epidemic', 'unrest', 'unpopular', 'aging'], cost: { pctGdp: 2.8 }, pc: 3,
      baseSuccess: 0.7, skills: [['stability', 0.14], ['tech', 0.06]],
      effects: {
        success: { self: { approval: 10, unrest: -7, stability: 4 },
          modifier: { label: 'Health coverage', turns: 16, growth: 0.1, unrest: -0.3 } },
        failure: { self: { approval: -5, unrest: 4 }, modifier: { label: 'Health system strain', turns: 6, growth: -0.15 } },
      } }),
  p('education-reform', 'Rebuild the Schools', 'domestic',
    'Teachers, buildings, curriculum. It pays back after you have left office.',
    { situational: ['young', 'techLag', 'stagnant', 'unrest'], cost: { pctGdp: 2 }, pc: 3,
      baseSuccess: 0.72, skills: [['tech', 0.12], ['stability', 0.1]],
      effects: {
        success: { self: { approval: 5, tech: 3 },
          modifier: { label: 'Schools programme', turns: 16, growth: 0.18, tech: 0.3 } },
        failure: { self: { approval: -4, unrest: 3 } },
      } }),
  p('devolution', 'Devolve Power to the Regions', 'domestic',
    'Give the provinces what they are already taking, and call it a settlement.',
    { situational: ['newState', 'unrest', 'fragile', 'borderChange', 'boiling'], cost: { pctGdp: 0.6 },
      pc: 4, risk: 'high', baseSuccess: 0.62, skills: [['stability', 0.18], ['influence', 0.06]],
      effects: {
        success: { self: { unrest: -12, stability: 5, approval: 3 },
          modifier: { label: 'Devolution settlement', turns: 14, unrest: -0.4 } },
        failure: { self: { unrest: 8, stability: -8, approval: -5 } },
      } }),
  p('emergency-powers', 'Assume Emergency Powers', 'domestic',
    'Rule by decree until the crisis passes, for a definition of "passes" you write.',
    { situational: ['boiling', 'coup', 'riot', 'disaster', 'war', 'epidemic'], cost: { pctGdp: 0.2 },
      pc: 4, risk: 'high', baseSuccess: 0.68, confirm: true, skills: [['stability', 0.18]],
      effects: {
        success: { self: { stability: 8, unrest: -8, approval: -6, influence: -4 },
          modifier: { label: 'Emergency rule', turns: 8, unrest: -0.5, growth: -0.15 } },
        failure: { self: { stability: -12, unrest: 14, approval: -12 } },
      } }),
  p('truth-commission', 'Truth and Reconciliation Commission', 'domestic',
    'Testimony, amnesty and a final report that satisfies nobody and settles it anyway.',
    { situational: ['coup', 'riot', 'conquest', 'occupied', 'casualties'], cost: { pctGdp: 0.4 }, pc: 4,
      baseSuccess: 0.64, skills: [['stability', 0.2], ['approval', 0.08]],
      effects: {
        success: { self: { stability: 8, unrest: -10, approval: 5 },
          modifier: { label: 'Reconciliation process', turns: 12, unrest: -0.35 } },
        failure: { self: { unrest: 9, stability: -5, approval: -6 } },
      } }),
  p('public-broadcaster', 'Rebuild the Public Broadcaster', 'domestic',
    'Charter, funding, and an editorial line that is independent in exactly the ways that suit you.',
    { situational: ['unpopular', 'cyber', 'fragile', 'riot'], cost: { pctGdp: 0.4 }, pc: 3,
      baseSuccess: 0.7, skills: [['influence', 0.14], ['stability', 0.08]],
      effects: {
        success: { self: { approval: 7, stability: 3, unrest: -4 },
          modifier: { label: 'Information environment', turns: 12, unrest: -0.25 } },
        failure: { self: { approval: -5, influence: -3 } },
      } }),
  p('disaster-agency', 'Standing Disaster Agency', 'domestic',
    'Warehouses, helicopters, and a chain of command that works at three in the morning.',
    { situational: ['disaster', 'epidemic', 'accident', 'famine'], cost: { pctGdp: 0.9 }, pc: 2,
      baseSuccess: 0.78, skills: [['stability', 0.16]],
      effects: {
        success: { self: { stability: 5, approval: 6, unrest: -4 },
          modifier: { label: 'Civil protection', turns: 14, unrest: -0.25 } },
        failure: { self: { approval: -3 } },
      } }),
  p('policing-reform', 'Reform the Police', 'domestic',
    'Oversight, retraining, and the resignation of everyone who liked it the old way.',
    { situational: ['riot', 'unrest', 'boiling', 'unpopular'], cost: { pctGdp: 0.7 }, pc: 4, risk: 'high',
      baseSuccess: 0.6, skills: [['stability', 0.16], ['approval', 0.1]],
      effects: {
        success: { self: { unrest: -11, approval: 6, stability: 3 },
          modifier: { label: 'Policing reform', turns: 12, unrest: -0.35 } },
        failure: { self: { unrest: 8, stability: -6, approval: -4 } },
      } }),
  p('early-election', 'Call an Early Election', 'domestic',
    'Ask for a mandate while you still might get one.',
    { situational: ['popular', 'unpopular', 'fragile', 'warWinning'], cost: { pctGdp: 0.2 }, pc: 5,
      risk: 'high', confirm: true, baseSuccess: 0.55, skills: [['approval', 0.3], ['influence', 0.06]],
      effects: {
        success: { self: { approval: 12, stability: 8, unrest: -5 },
          modifier: { label: 'Fresh mandate', turns: 12, growth: 0.1 } },
        failure: { self: { approval: -12, stability: -10, unrest: 8 } },
      } }),
  p('civil-service-reform', 'Rebuild the Civil Service', 'domestic',
    'Merit entry, decent pay, and a decade before you can tell whether it worked.',
    { situational: ['fragile', 'stagnant', 'newState', 'coup'], cost: { pctGdp: 0.8 }, pc: 3,
      baseSuccess: 0.7, skills: [['stability', 0.18], ['tech', 0.06]],
      effects: {
        success: { self: { stability: 7, tech: 2 },
          modifier: { label: 'Capable state', turns: 16, growth: 0.14, unrest: -0.15 } },
        failure: { self: { stability: -4, approval: -3 } },
      } }),
  p('language-policy', 'National Language and Identity Act', 'domestic',
    'Decide officially who the country is for. Half of it will disagree.',
    { situational: ['newState', 'refugees', 'unrest', 'conquest', 'occupier'], cost: { pctGdp: 0.3 },
      pc: 4, risk: 'high', baseSuccess: 0.58, skills: [['stability', 0.14]],
      effects: {
        success: { self: { stability: 6, approval: 6, unrest: 3 } },
        failure: { self: { unrest: 14, stability: -7, approval: -6 } },
      } }),
  p('rural-programme', 'Rural Development Programme', 'domestic',
    'Roads, clinics and a mobile signal for the half of the country that decides elections.',
    { situational: ['agrarian', 'unrest', 'famine', 'stagnant'], cost: { pctGdp: 1.4 }, pc: 2,
      baseSuccess: 0.74, skills: [['stability', 0.14]],
      effects: {
        success: { self: { approval: 7, unrest: -6 }, modifier: { label: 'Rural investment', turns: 12, growth: 0.18 } },
        failure: { self: { approval: -3, unrest: 3 } },
      } }),
  p('public-health-campaign', 'Mass Vaccination Campaign', 'domestic',
    'Cold chain, clinics, and a rumour to outrun in every district.',
    { situational: ['epidemic', 'unrest', 'young'], cost: { pctGdp: 0.8 }, pc: 2, baseSuccess: 0.76,
      skills: [['tech', 0.14], ['stability', 0.08]],
      effects: {
        success: { self: { approval: 7, unrest: -6, stability: 3, population: 0.4 },
          modifier: { label: 'Outbreak contained', turns: 8, growth: 0.14 } },
        failure: { self: { approval: -6, unrest: 7 }, modifier: { label: 'Outbreak spreading', turns: 6, growth: -0.3 } },
      } }),
  p('urban-renewal', 'Urban Renewal Programme', 'domestic',
    'Transit, parks and a waterfront. It photographs well, which is half the point.',
    { situational: ['riot', 'unrest', 'growing', 'unpopular'], cost: { pctGdp: 1.6 }, pc: 2,
      baseSuccess: 0.74, skills: [['stability', 0.1]],
      effects: {
        success: { self: { approval: 6, unrest: -5 }, modifier: { label: 'Urban renewal', turns: 12, growth: 0.16 } },
        failure: { self: { approval: -4 } },
      } }),
  p('national-mobilisation', 'National Mobilisation Act', 'domestic',
    'Direct labour, requisition industry, and suspend the arguments until it is over.',
    { situational: ['war', 'warLosing', 'occupied', 'brink'], cost: { pctGdp: 1 }, pc: 5, risk: 'high',
      confirm: true, baseSuccess: 0.64, skills: [['stability', 0.18]],
      effects: {
        success: { self: { readiness: 12, military: 4, unrest: 8, approval: -5 },
          modifier: { label: 'Total mobilisation', turns: 10, growth: -0.5, readiness: 0.6 } },
        failure: { self: { unrest: 16, stability: -8, approval: -10, readiness: 3 } },
      } }),

  // ══ Intelligence ══════════════════════════════════════════════════════════
  p('signals-agency', 'Expand the Signals Agency', 'intelligence',
    'Cables, satellites and a legal opinion nobody outside the building will read.',
    { situational: ['cyber', 'tension', 'war', 'attack', 'techLead'], cost: { pctGdp: 1.1 }, pc: 3,
      covert: true, baseSuccess: 0.72, skills: [['tech', 0.2]],
      effects: {
        success: { self: { tech: 3, influence: 2 },
          modifier: { label: 'Signals coverage', turns: 14, tech: 0.25, unrest: -0.1 } },
        failure: { self: { approval: -4, stability: -2 } },
      } }),
  p('counter-terror-programme', 'Counter-Terror Programme', 'intelligence',
    'Watchlists, arrests and a standing argument with your own courts.',
    { situational: ['attack', 'riot', 'refugees', 'boiling'], cost: { pctGdp: 0.9 }, pc: 3, risk: 'high',
      covert: true, baseSuccess: 0.68, skills: [['stability', 0.16], ['tech', 0.1]],
      effects: {
        success: { self: { stability: 6, unrest: -6, approval: 4 },
          modifier: { label: 'Counter-terror posture', turns: 10, unrest: -0.3 } },
        failure: { self: { unrest: 9, approval: -7, stability: -4 } },
      } }),
  p('penetrate-command', 'Penetrate Their Command', 'intelligence',
    'A source in the room where the orders are given. Years of work, one careless quarter to lose.',
    { situational: ['war', 'warStalled', 'hostileNeighbour', 'escalation'], cost: { pctGdp: 0.7 },
      pc: 4, target: 'nation', covert: true, risk: 'high', baseSuccess: 0.5,
      skills: [['tech', 0.16], ['influence', 0.1]],
      effects: {
        success: { self: { influence: 3, readiness: 4 }, target: { readiness: -6, stability: -3 },
          modifier: { label: 'Inside their command', turns: 8, readiness: 0.4 } },
        failure: { self: { influence: -5, approval: -3 }, relation: -20, worldTension: 4 },
      } }),
  p('influence-operation', 'Run an Influence Operation', 'intelligence',
    'Their newspapers, their comment sections, their election, your talking points.',
    { situational: ['hostileNeighbour', 'tension', 'isolated', 'feared'], cost: { pctGdp: 0.6 },
      pc: 4, target: 'nation', covert: true, risk: 'high', baseSuccess: 0.54,
      skills: [['influence', 0.18], ['tech', 0.12]],
      effects: {
        success: { target: { stability: -6, unrest: 7, approval: -5 }, self: { influence: 3 } },
        failure: { self: { influence: -7, approval: -5 }, relation: -24, worldTension: 5 },
      } }),
  p('security-service-purge', 'Purge the Security Service', 'intelligence',
    'Somebody in that building is working for somebody else. Finding out which costs you the rest.',
    { situational: ['coup', 'cyber', 'fragile', 'attack'], cost: { pctGdp: 0.3 }, pc: 4, risk: 'high',
      covert: true, baseSuccess: 0.58, skills: [['stability', 0.18]],
      effects: {
        success: { self: { stability: 8, influence: 2 }, modifier: { label: 'Clean service', turns: 10, unrest: -0.2 } },
        failure: { self: { stability: -9, unrest: 6, readiness: -4 } },
      } }),
  p('sabotage-programme', 'Sabotage Their Logistics', 'intelligence',
    'Rail junctions, transformers and fuel depots, none of it traceable on paper.',
    { situational: ['war', 'warLosing', 'warStalled', 'occupied'], cost: { pctGdp: 0.8 }, pc: 4,
      target: 'nation', covert: true, risk: 'high', baseSuccess: 0.56,
      warEffect: { warScore: 9, enemyExhaustion: 7 },
      skills: [['tech', 0.16], ['military', 0.08]],
      effects: {
        success: { target: { readiness: -8, stability: -4 }, self: { readiness: 2 }, worldTension: 3 },
        failure: { self: { influence: -6, readiness: -2 }, relation: -20, worldTension: 6 },
      } }),
  p('defector-programme', 'Run the Defector Pipeline', 'intelligence',
    'Money, papers and a new life for anyone who walks out with a briefcase.',
    { situational: ['hostileNeighbour', 'war', 'coup', 'pariah'], cost: { pctGdp: 0.4 }, pc: 3,
      target: 'nation', covert: true, baseSuccess: 0.62, skills: [['influence', 0.14], ['tech', 0.08]],
      effects: {
        success: { self: { tech: 3, influence: 3 }, target: { stability: -4, influence: -3 } },
        failure: { self: { influence: -3 }, relation: -12 },
      } }),
  p('cyber-defence-command', 'Stand Up a Cyber Defence Command', 'intelligence',
    'Assume they are already inside, and build for the day you can prove it.',
    { situational: ['cyber', 'techLag', 'attack', 'war', 'accident'], cost: { pctGdp: 1 }, pc: 3,
      baseSuccess: 0.74, skills: [['tech', 0.22]],
      effects: {
        success: { self: { tech: 4, stability: 4 },
          modifier: { label: 'Hardened networks', turns: 14, tech: 0.2, unrest: -0.1 } },
        failure: { self: { tech: 1, approval: -3 } },
      } }),
  p('surveillance-state', 'National Surveillance Programme', 'intelligence',
    'Cameras, identity, and a database that will still exist under the next government.',
    { situational: ['boiling', 'riot', 'attack', 'coup', 'techLead'], cost: { pctGdp: 1.2 }, pc: 4,
      risk: 'high', confirm: true, baseSuccess: 0.68, skills: [['tech', 0.18], ['stability', 0.1]],
      effects: {
        success: { self: { stability: 8, unrest: -7, approval: -5, influence: -3 },
          modifier: { label: 'Surveillance apparatus', turns: 16, unrest: -0.4 } },
        failure: { self: { unrest: 12, approval: -10, stability: -4 } },
      } }),
  p('nuclear-intelligence', 'Watch Their Arsenal', 'intelligence',
    'Every silo, every boat, every convoy. It is the only file that never closes.',
    { situational: ['nuclear', 'brink', 'nuclearUsed', 'escalation'], cost: { pctGdp: 0.8 }, pc: 3,
      target: 'nation', covert: true, baseSuccess: 0.66, skills: [['tech', 0.2]],
      effects: {
        success: { self: { readiness: 5, tech: 2, stability: 3 }, worldTension: -2,
          modifier: { label: 'Warning time', turns: 12, readiness: 0.25 } },
        failure: { self: { readiness: -2 }, relation: -12, worldTension: 3 },
      } }),
  p('proxy-support', 'Arm the Proxy', 'intelligence',
    'Somebody else’s war, your crates, and deniability that lasts about a year.',
    { situational: ['warNextDoor', 'hostileNeighbour', 'neighbourCrisis', 'feared'], cost: { pctGdp: 1 },
      pc: 4, target: 'nation', covert: true, risk: 'high', baseSuccess: 0.56,
      skills: [['military', 0.14], ['influence', 0.1]],
      effects: {
        success: { target: { stability: -8, unrest: 9, military: -3 }, self: { influence: 2 }, worldTension: 5 },
        failure: { self: { influence: -8, approval: -5 }, relation: -26, worldTension: 8 },
      } }),
  p('economic-intelligence', 'Economic Intelligence Bureau', 'intelligence',
    'Know what they are buying, from whom, and at what price, before their own ministry does.',
    { situational: ['sanctioned', 'commodityShock', 'exporter', 'financial'], cost: { pctGdp: 0.5 },
      pc: 2, covert: true, baseSuccess: 0.74, skills: [['tech', 0.14], ['influence', 0.1]],
      effects: {
        success: { self: { influence: 3, tech: 2 }, modifier: { label: 'Commercial intelligence', turns: 12, growth: 0.16 } },
        failure: { self: { influence: -2 } },
      } }),

  // ══ Technology ════════════════════════════════════════════════════════════
  p('national-ai-programme', 'National AI Programme', 'technology',
    'Compute, data, and the people who can use both, before somebody else has all three.',
    { situational: ['techLag', 'techLead', 'growing', 'breakthrough'], cost: { pctGdp: 2.4 }, pc: 4,
      baseSuccess: 0.66, skills: [['tech', 0.24]],
      effects: {
        success: { self: { tech: 8, influence: 3 },
          modifier: { label: 'AI programme', turns: 16, growth: 0.3, tech: 0.4 } },
        failure: { self: { tech: 2, approval: -3 }, modifier: { label: 'Stranded compute', turns: 6, growth: -0.15 } },
      } }),
  p('fusion-programme', 'Fusion Demonstration Programme', 'technology',
    'Thirty years away, as it has been for sixty. Somebody is going to be right eventually.',
    { situational: ['techLead', 'rich', 'energy', 'breakthrough'], cost: { pctGdp: 2.6 }, pc: 4,
      risk: 'high', baseSuccess: 0.5, skills: [['tech', 0.28]],
      effects: {
        success: { self: { tech: 9, influence: 5 },
          modifier: { label: 'Fusion programme', turns: 20, growth: 0.32, tech: 0.4 } },
        failure: { self: { tech: 2, approval: -4 }, modifier: { label: 'Fusion overruns', turns: 8, growth: -0.2 } },
      } }),
  p('biotech-programme', 'Biotechnology Initiative', 'technology',
    'Sequencing, manufacturing and a regulator willing to move at the speed of the science.',
    { situational: ['epidemic', 'aging', 'techLag', 'breakthrough'], cost: { pctGdp: 1.6 }, pc: 3,
      baseSuccess: 0.68, skills: [['tech', 0.2]],
      effects: {
        success: { self: { tech: 6, approval: 3 },
          modifier: { label: 'Biotech base', turns: 14, growth: 0.24, tech: 0.3 } },
        failure: { self: { tech: 1, approval: -2 } },
      } }),
  p('nuclear-power', 'Civil Nuclear Build-Out', 'technology',
    'Twelve reactors, one design, and a waste plan that outlives the republic.',
    { situational: ['energy', 'commodityShock', 'accident', 'growing', 'techLag'], cost: { pctGdp: 2.8 },
      pc: 4, risk: 'high', baseSuccess: 0.62, skills: [['tech', 0.2], ['stability', 0.08]],
      effects: {
        success: { self: { tech: 5, unrest: 3 },
          modifier: { label: 'Nuclear baseload', turns: 18, growth: 0.3 } },
        failure: { self: { unrest: 9, approval: -7 }, modifier: { label: 'Reactor programme stalled', turns: 8, growth: -0.25 } },
      } }),
  p('satellite-constellation', 'Launch a Satellite Constellation', 'technology',
    'Imaging, comms and navigation you do not have to ask anybody for.',
    { situational: ['techLead', 'war', 'tension', 'maritime', 'isolated'], cost: { pctGdp: 1.8 }, pc: 3,
      baseSuccess: 0.66, skills: [['tech', 0.22]],
      effects: {
        success: { self: { tech: 5, readiness: 5, influence: 3 },
          modifier: { label: 'Own constellation', turns: 16, tech: 0.3, readiness: 0.2 } },
        failure: { self: { tech: 1, treasuryPctGdp: -0.6 } },
      } }),
  p('research-universities', 'Fund the Research Universities', 'technology',
    'Chairs, laboratories and doctoral places. The slowest instrument you own, and the surest.',
    { situational: ['techLag', 'young', 'stagnant', 'calm'], cost: { pctGdp: 1.2 }, pc: 2,
      baseSuccess: 0.78, skills: [['tech', 0.16]],
      effects: {
        success: { self: { tech: 4, approval: 2 },
          modifier: { label: 'Research base', turns: 18, tech: 0.35, growth: 0.14 } },
        failure: { self: { tech: 1 } },
      } }),
  p('tech-sovereignty', 'Technological Sovereignty Act', 'technology',
    'Domestic chips, domestic clouds, domestic models — at roughly twice the price.',
    { situational: ['sanctioned', 'cyber', 'pariah', 'techLag', 'isolated'], cost: { pctGdp: 2.2 },
      pc: 4, risk: 'high', baseSuccess: 0.6, skills: [['tech', 0.2], ['stability', 0.06]],
      effects: {
        success: { self: { tech: 6, influence: 2 },
          modifier: { label: 'Sovereign technology stack', turns: 16, tech: 0.3, growth: -0.08 } },
        failure: { self: { tech: 2, approval: -4 }, modifier: { label: 'Import substitution failing', turns: 8, growth: -0.25 } },
      } }),
  p('water-programme', 'National Water Programme', 'technology',
    'Desalination, reuse and pipelines, because the alternative is a war about a river.',
    { situational: ['famine', 'disaster', 'agrarian', 'unrest'], cost: { pctGdp: 1.8 }, pc: 3,
      baseSuccess: 0.72, skills: [['tech', 0.16], ['stability', 0.08]],
      effects: {
        success: { self: { tech: 3, unrest: -6, approval: 5 },
          modifier: { label: 'Water security', turns: 16, growth: 0.2, unrest: -0.2 } },
        failure: { self: { approval: -4, unrest: 4 } },
      } }),
  p('quantum-programme', 'Quantum Programme', 'technology',
    'Useless for a decade, decisive afterwards, and it breaks everyone’s cryptography including yours.',
    { situational: ['techLead', 'cyber', 'rich', 'breakthrough'], cost: { pctGdp: 1.4 }, pc: 3,
      risk: 'high', baseSuccess: 0.56, skills: [['tech', 0.26]],
      effects: {
        success: { self: { tech: 7, influence: 3 }, modifier: { label: 'Quantum lead', turns: 16, tech: 0.35 } },
        failure: { self: { tech: 1 } },
      } }),
  p('rare-earth-processing', 'Rare-Earth Processing Plants', 'technology',
    'Digging it up was never the hard part. Refining it without poisoning a province is.',
    { situational: ['resource', 'sanctioned', 'techLag', 'exporter'], cost: { pctGdp: 1.5 }, pc: 3,
      baseSuccess: 0.66, skills: [['tech', 0.18]],
      effects: {
        success: { self: { tech: 4, influence: 4, unrest: 2 },
          modifier: { label: 'Processing capacity', turns: 14, growth: 0.26 } },
        failure: { self: { unrest: 6, approval: -4 } },
      } }),
  p('open-standards', 'Publish the Standards', 'technology',
    'Give the specification away and let the world build on your foundations.',
    { situational: ['techLead', 'influential', 'breakthrough', 'isolated'], cost: { pctGdp: 0.3 }, pc: 2,
      baseSuccess: 0.76, skills: [['tech', 0.14], ['influence', 0.12]],
      effects: {
        success: { self: { influence: 6, tech: -1 },
          modifier: { label: 'Standards leadership', turns: 14, influence: 0.35, growth: 0.12 } },
        failure: { self: { tech: -2, influence: 1 } },
      } }),
  p('brain-gain', 'Recruit Abroad', 'technology',
    'Visas, laboratories and salaries for other countries’ best people. It works, and they notice.',
    { situational: ['techLag', 'rich', 'aging', 'breakthrough'], cost: { pctGdp: 0.8 }, pc: 3,
      baseSuccess: 0.7, skills: [['tech', 0.16], ['influence', 0.1]],
      effects: {
        success: { self: { tech: 5, population: 0.3 },
          modifier: { label: 'Talent inflow', turns: 14, tech: 0.3, growth: 0.16 } },
        failure: { self: { tech: 1, approval: -3, unrest: 3 } },
      } }),

  // ══ War room ══════════════════════════════════════════════════════════════
  p('encircle', 'Attempt an Encirclement', 'war',
    'Pinch behind them and close the bag. If it works the war shortens by a year.',
    { situational: ['war', 'warWinning', 'warStalled'], cost: { pctGdp: 1.4 }, pc: 4, risk: 'high',
      baseSuccess: 0.52, skills: [['military', 0.22], ['readiness', 0.16]],
      warEffect: { warScore: 22, enemyExhaustion: 14, ownExhaustion: 8, casualties: 24_000 },
      warEffectOnFailure: { warScore: -14, ownExhaustion: 16, casualties: 38_000 },
      effects: {
        success: { self: { approval: 6, readiness: -6 } },
        failure: { self: { approval: -9, readiness: -10, unrest: 6 } },
      } }),
  p('fighting-withdrawal', 'Fighting Withdrawal', 'war',
    'Give ground on your terms rather than lose an army on theirs.',
    { situational: ['warLosing', 'warExhausted', 'occupied'], cost: { pctGdp: 0.6 }, pc: 3,
      baseSuccess: 0.72, skills: [['military', 0.14], ['readiness', 0.12]],
      warEffect: { warScore: -6, ownExhaustion: -10 },
      warEffectOnFailure: { warScore: -16, ownExhaustion: 6, casualties: 26_000 },
      effects: {
        success: { self: { readiness: 5, approval: -3 } },
        failure: { self: { readiness: -8, approval: -8, unrest: 5 } },
      } }),
  p('winter-quarters', 'Go Into Winter Quarters', 'war',
    'Stop attacking, rebuild the formations, and let both sides count what is left.',
    { situational: ['warExhausted', 'warStalled', 'casualties'], cost: { pctGdp: 0.7 }, pc: 2,
      baseSuccess: 0.8, skills: [['stability', 0.12]],
      warEffect: { ownExhaustion: -16 },
      effects: {
        success: { self: { readiness: 8, unrest: -3 }, modifier: { label: 'Refitting', turns: 4, readiness: 0.4 } },
        failure: { self: { readiness: 2 } },
      } }),
  p('occupation-government', 'Stand Up an Occupation Government', 'war',
    'Ministries, currency and police for ground that is not yours. It is the expensive half of winning.',
    { situational: ['occupier', 'conquest', 'warWinning'], cost: { pctGdp: 1.6 }, pc: 4,
      baseSuccess: 0.62, skills: [['stability', 0.18], ['influence', 0.08]],
      effects: {
        success: { self: { stability: 4, unrest: -4, influence: 2 },
          modifier: { label: 'Occupation administration', turns: 12, growth: -0.1, unrest: -0.2 } },
        failure: { self: { unrest: 10, stability: -6, readiness: -4 },
          modifier: { label: 'Ungoverned occupation', turns: 8, unrest: 0.6, growth: -0.25 } },
      } }),
  p('war-loan', 'Float a War Loan', 'war',
    'Ask the public to fund it directly. They will, once.',
    { situational: ['war', 'debt', 'tight', 'popular'], cost: { pctGdp: 0.1 }, pc: 2, baseSuccess: 0.7,
      skills: [['approval', 0.2], ['stability', 0.1]],
      effects: {
        success: { self: { treasuryPctGdp: 3.5, approval: 2 },
          modifier: { label: 'War loan service', turns: 12, growth: -0.12 } },
        failure: { self: { approval: -6, treasuryPctGdp: 0.8, unrest: 4 } },
      } }),
  p('strategic-bombardment', 'Strategic Bombardment Campaign', 'war',
    'Hit what makes their war possible, and accept what that does to your name.',
    { situational: ['war', 'warStalled', 'strongArmy', 'casualties'], cost: { pctGdp: 1.8 }, pc: 4,
      risk: 'high', confirm: true, baseSuccess: 0.6, skills: [['military', 0.2], ['tech', 0.12]],
      warEffect: { warScore: 16, enemyExhaustion: 16, casualties: 30_000 },
      warEffectOnFailure: { warScore: -6, ownExhaustion: 8, casualties: 18_000 },
      effects: {
        success: { self: { influence: -6 }, worldTension: 7 },
        failure: { self: { influence: -9, approval: -6 }, worldTension: 9 },
      } }),
  p('naval-blockade', 'Blockade Their Coast', 'war',
    'Nothing in, nothing out. It is slower than a battle and harder to answer.',
    { situational: ['war', 'maritime', 'warStalled', 'warWinning'], cost: { pctGdp: 1.2 }, pc: 3,
      risk: 'high', baseSuccess: 0.62, skills: [['military', 0.18], ['readiness', 0.12]],
      warEffect: { warScore: 12, enemyExhaustion: 18 },
      warEffectOnFailure: { warScore: -8, ownExhaustion: 10 },
      effects: {
        success: { self: { influence: -3 }, worldTension: 6 },
        failure: { self: { readiness: -6, influence: -5 }, worldTension: 4 },
      } }),
  p('separate-peace', 'Offer a Separate Peace', 'war',
    'Talk to one of them without the others in the room, and break the coalition instead of the front.',
    { situational: ['warLosing', 'warExhausted', 'warStalled'], cost: { pctGdp: 0.3 }, pc: 4,
      target: 'nation', seeksPeace: true, baseSuccess: 0.56, skills: [['influence', 0.24]],
      effects: {
        success: { self: { influence: 4, approval: 5 }, relation: 26, worldTension: -5 },
        failure: { self: { influence: -4, approval: -4 }, relation: -6 },
      } }),
];
