// The quick shelf.
//
// A hundred-odd one-capital orders, each of which declares — in `situational` —
// the circumstances it is an answer to. Nothing here is offered unless the
// world has actually produced the situation it addresses, so the tab is a short
// list of things a chief of staff would put in front of you this morning rather
// than a catalogue you scroll past.
//
// The rules for a quick order:
//   · one point of political capital, occasionally two
//   · cheap enough that taking one is never the reason you cannot afford a
//     real programme
//   · specific. "Address the Nation" is a quick order; "Industrial Strategy"
//     is not
//   · it should sound like something a government did, not like a stat block

/** Defaults, so each order below is four lines of what makes it different. */
function q(id, name, category, blurb, opts = {}) {
  return {
    id,
    name,
    category,
    blurb,
    quick: true,
    target: 'none',
    pc: 1,
    risk: 'low',
    baseSuccess: 0.78,
    cost: { pctGdp: 0.1 },
    skills: [],
    ...opts,
  };
}

/** @type {Array<object>} */
export const QUICK_ORDERS = [
  // ── The street ────────────────────────────────────────────────────────────
  q('riot-inquiry', 'Independent Inquiry into the Policing', 'domestic',
    'Name a judge, give them subpoena powers, and accept that you will not like the report.',
    { situational: ['riot', 'unrest'], pc: 2, baseSuccess: 0.7, risk: 'medium',
      skills: [['stability', 0.14]],
      effects: {
        success: { self: { unrest: -8, approval: 3, stability: 3 } },
        failure: { self: { unrest: 4, approval: -5, stability: -2 } },
      } }),
  q('meet-organisers', 'Meet the Organisers', 'domestic',
    'Invite the people leading the marches into the building. It legitimises them, and it works.',
    { situational: ['unrest', 'riot'], cost: { pctGdp: 0.02 }, baseSuccess: 0.72, risk: 'medium',
      skills: [['approval', 0.16]],
      effects: {
        success: { self: { unrest: -9, approval: 4 } },
        failure: { self: { unrest: 3, approval: -6, stability: -2 } },
      } }),
  q('release-detainees', 'Release the Detainees', 'domestic',
    'Empty the holding cells before the hunger strikes start. Cheap, and it defuses.',
    { situational: ['riot', 'boiling'], cost: { pctGdp: 0.01 },
      effects: {
        success: { self: { unrest: -7, approval: 2, stability: -1 } },
        failure: { self: { unrest: 2, approval: -3 } },
      } }),
  q('deploy-gendarmerie', 'Deploy the Gendarmerie', 'domestic',
    'Not the army, not the police. Everyone understands the distinction and nobody likes it.',
    { situational: ['riot', 'boiling'], cost: { pctGdp: 0.18 }, risk: 'medium',
      skills: [['stability', 0.16], ['readiness', 0.08]],
      effects: {
        success: { self: { unrest: -11, stability: 2, approval: -3 } },
        failure: { self: { unrest: 8, stability: -5, approval: -8 } },
      } }),
  q('youth-jobs', 'Emergency Youth Employment Scheme', 'domestic',
    'Put a hundred thousand under-twenty-fives on a payroll by the end of the month.',
    { situational: ['unrest', 'young', 'stagnant'], cost: { pctGdp: 0.45 }, pc: 2,
      effects: {
        success: { self: { unrest: -6, approval: 5 }, modifier: { label: 'Jobs programme', turns: 5, growth: 0.14 } },
        failure: { self: { approval: -3, unrest: 2 } },
      } }),
  q('open-archives', 'Open the Archives', 'domestic',
    'Publish what the last government did. Popular, and it makes an enemy of everyone in it.',
    { situational: ['unpopular', 'fragile'], cost: { pctGdp: 0.02 }, risk: 'medium',
      skills: [['approval', 0.12]],
      effects: {
        success: { self: { approval: 7, unrest: -3, stability: -2 } },
        failure: { self: { approval: -5, stability: -4, unrest: 4 } },
      } }),
  q('sack-the-minister', 'Sack the Minister', 'domestic',
    'Somebody has to go. Pick the one whose faction you can afford to lose.',
    { situational: ['unpopular', 'riot', 'accident'], cost: { pctGdp: 0.01 },
      effects: {
        success: { self: { approval: 5, unrest: -3, stability: -1 } },
        failure: { self: { approval: -2, stability: -3 } },
      } }),
  q('national-service', 'Announce National Service', 'domestic',
    'Two years, everyone, no exemptions worth having. It is popular with everyone too old for it.',
    { situational: ['hollowArmy', 'war', 'young'], cost: { pctGdp: 0.5 }, pc: 2, risk: 'medium',
      skills: [['stability', 0.12]],
      effects: {
        success: { self: { readiness: 8, military: 2, unrest: 4, approval: -2 } },
        failure: { self: { unrest: 9, approval: -7, readiness: 1 } },
      } }),
  q('fuel-subsidy', 'Restore the Fuel Subsidy', 'economy',
    'Put the pump price back where it was. The street stops, and the deficit starts.',
    { situational: ['unrest', 'inflation', 'commodityShock'], cost: { pctGdp: 0.7 },
      effects: {
        success: { self: { unrest: -8, approval: 6 }, modifier: { label: 'Fuel subsidy', turns: 5, growth: -0.1 } },
        failure: { self: { approval: -3, unrest: 3 } },
      } }),
  q('rent-freeze', 'Freeze the Rents', 'domestic',
    'Popular in every city and disastrous in all of them, eventually.',
    { situational: ['unrest', 'inflation'], cost: { pctGdp: 0.05 }, risk: 'medium',
      effects: {
        success: { self: { unrest: -6, approval: 6 }, modifier: { label: 'Rent controls', turns: 6, growth: -0.14 } },
        failure: { self: { approval: -4, unrest: 3 } },
      } }),
  q('amnesty', 'Declare a General Amnesty', 'domestic',
    'Everyone convicted of a political offence walks out on Friday. It is a gamble, publicly made.',
    { situational: ['boiling', 'fragile'], cost: { pctGdp: 0.02 }, pc: 2, risk: 'high',
      skills: [['approval', 0.14]],
      effects: {
        success: { self: { unrest: -14, approval: 8, stability: 2 } },
        failure: { self: { unrest: 6, approval: -6, stability: -6 } },
        backfire: { self: { unrest: 14, approval: -12, stability: -10 } },
      } }),
  q('call-election', 'Call an Early Election', 'domestic',
    'Go to the country before the country comes to you.',
    { situational: ['unpopular', 'unrest'], cost: { pctGdp: 0.15 }, pc: 3, risk: 'high',
      skills: [['approval', 0.3]],
      effects: {
        success: { self: { approval: 16, stability: 6, unrest: -6 } },
        failure: { self: { approval: -10, stability: -8, unrest: 5 } },
        backfire: { self: { approval: -20, stability: -14, unrest: 12 } },
      } }),
  q('pay-the-nurses', 'Settle with the Health Unions', 'domestic',
    'Give them the number. It costs, and it ends the thing that was on the news every night.',
    { situational: ['unrest', 'epidemic'], cost: { pctGdp: 0.35 },
      effects: {
        success: { self: { unrest: -7, approval: 6, stability: 2 } },
        failure: { self: { approval: -4, unrest: 4 } },
      } }),
  q('curfew-lift', 'Lift the Emergency Measures', 'domestic',
    'Give back the powers you took. Doing it voluntarily is worth more than being made to.',
    { situational: ['calm', 'popular'], cost: { pctGdp: 0.01 },
      effects: {
        success: { self: { approval: 5, stability: 4, unrest: -2 } },
        failure: { self: { stability: -2, unrest: 3 } },
      } }),
  q('language-concession', 'Concede on the Language Law', 'domestic',
    'Let the province teach in its own tongue. It costs nothing and it removes a grievance.',
    { situational: ['unrest', 'fragile'], cost: { pctGdp: 0.05 }, pc: 2,
      effects: {
        success: { self: { unrest: -9, stability: 4, approval: -2 } },
        failure: { self: { unrest: 3, approval: -5, stability: -2 } },
      } }),

  // ── The books ─────────────────────────────────────────────────────────────
  q('bond-auction', 'Bring Forward the Bond Auction', 'economy',
    'Go to market before the window closes. The coupon will be ugly and the cash is real.',
    { situational: ['debt', 'tight'], cost: { pctGdp: 0 }, baseSuccess: 0.74, risk: 'medium',
      skills: [['stability', 0.16]],
      effects: {
        success: { self: { treasuryPctGdp: 2.6 }, modifier: { label: 'Heavier debt service', turns: 6, revenue: 0, growth: -0.08 } },
        failure: { self: { treasuryPctGdp: 0.6, influence: -2, approval: -3 } },
      } }),
  q('sell-the-airline', 'Privatise the Flag Carrier', 'economy',
    'Sell the thing everyone is sentimental about and nobody wants to fund.',
    { situational: ['debt', 'tight'], cost: { pctGdp: 0 }, pc: 2, risk: 'medium',
      skills: [['tech', 0.1], ['stability', 0.08]],
      effects: {
        success: { self: { treasuryPctGdp: 1.8, approval: -4, unrest: 2 } },
        failure: { self: { approval: -7, unrest: 5 } },
      } }),
  q('windfall-tax', 'Windfall Levy on the Energy Majors', 'economy',
    'They had a very good year and everyone knows the number.',
    { situational: ['energy', 'commodityShock', 'tight'], cost: { pctGdp: 0 }, pc: 2, risk: 'medium',
      skills: [['stability', 0.14]],
      effects: {
        success: { self: { treasuryPctGdp: 1.6, approval: 5 }, modifier: { label: 'Investment chill', turns: 4, growth: -0.12 } },
        failure: { self: { approval: -3 }, modifier: { label: 'Investment chill', turns: 5, growth: -0.22 } },
      } }),
  q('capital-controls', 'Impose Capital Controls', 'economy',
    'Shut the door. The money that is out stays out, and the money that is in stops leaving.',
    { situational: ['financial', 'debt'], cost: { pctGdp: 0.1 }, pc: 2, risk: 'high',
      skills: [['stability', 0.16]],
      effects: {
        success: { self: { treasuryPctGdp: 0.8, influence: -3 }, modifier: { label: 'Capital controls', turns: 5, growth: -0.1 } },
        failure: { self: { influence: -6, unrest: 5 }, modifier: { label: 'Capital flight', turns: 5, growth: -0.4 } },
      } }),
  q('rate-hike', 'Take the Policy Rate Up', 'economy',
    'Break the price spiral by breaking something else. The bank will take the blame if you let it.',
    { situational: ['inflation', 'financial'], cost: { pctGdp: 0 }, risk: 'medium',
      skills: [['tech', 0.1], ['stability', 0.1]],
      effects: {
        success: { self: { unrest: -4 }, modifier: { label: 'Tight money', turns: 4, growth: -0.18 } },
        failure: { self: { unrest: 4, approval: -4 }, modifier: { label: 'Tight money', turns: 5, growth: -0.34 } },
      } }),
  q('strategic-reserve', 'Release the Strategic Reserve', 'economy',
    'Put the stockpile on the market. It moves the price for about six weeks.',
    { situational: ['commodityShock', 'energy', 'inflation'], cost: { pctGdp: 0.05 },
      effects: {
        success: { self: { unrest: -5, approval: 4 }, modifier: { label: 'Reserve drawdown', turns: 3, growth: 0.1 } },
        failure: { self: { approval: -3 } },
      } }),
  q('food-imports', 'Emergency Grain Imports', 'economy',
    'Buy at whatever it costs. A bread queue is a political event, not an economic one.',
    { situational: ['famine', 'agrarian', 'inflation'], cost: { pctGdp: 0.5 },
      effects: {
        success: { self: { unrest: -9, approval: 5 } },
        failure: { self: { unrest: 5, approval: -6 } },
      } }),
  q('special-economic-zone', 'Designate a Special Economic Zone', 'economy',
    'One port, one set of rules, one exception to everything. It usually works and never generalises.',
    { situational: ['stagnant', 'maritime', 'exporter'], cost: { pctGdp: 0.4 }, pc: 2,
      skills: [['tech', 0.12]],
      effects: {
        success: { modifier: { label: 'Special economic zone', turns: 10, growth: 0.24 }, self: { influence: 1 } },
        failure: { self: { treasuryPctGdp: -0.2, approval: -2 } },
      } }),
  q('tax-amnesty', 'Offshore Tax Amnesty', 'economy',
    'Bring it home, pay a fraction, ask no questions. Deeply unedifying and highly effective.',
    { situational: ['debt', 'tight'], cost: { pctGdp: 0 }, risk: 'medium',
      skills: [['stability', 0.12]],
      effects: {
        success: { self: { treasuryPctGdp: 1.4, approval: -3 } },
        failure: { self: { approval: -6, unrest: 3 } },
      } }),
  q('cut-the-subsidies', 'Withdraw the Subsidies', 'economy',
    'The IMF will approve. Nobody else will.',
    { situational: ['debt'], cost: { pctGdp: 0 }, pc: 2, risk: 'high',
      skills: [['stability', 0.18]],
      effects: {
        success: { self: { treasuryPctGdp: 2, unrest: 6, approval: -8 } },
        failure: { self: { unrest: 14, approval: -14, stability: -5 } },
      } }),
  q('open-the-fund', 'Open a Sovereign Wealth Fund', 'economy',
    'Put the surplus somewhere it compounds instead of somewhere it gets spent.',
    { situational: ['rich', 'energy'], cost: { pctGdp: 1.2 }, pc: 2,
      skills: [['tech', 0.1]],
      effects: {
        success: { modifier: { label: 'Sovereign fund', turns: 14, growth: 0.16, revenue: 0 }, self: { influence: 2 } },
        failure: { self: { treasuryPctGdp: -0.4 } },
      } }),
  q('infrastructure-bond', 'Issue a Diaspora Bond', 'economy',
    'Ask the people who left to fund the country they left. Surprisingly many say yes.',
    { situational: ['tight', 'debt', 'isolated'], cost: { pctGdp: 0.05 }, baseSuccess: 0.7,
      skills: [['influence', 0.16]],
      effects: {
        success: { self: { treasuryPctGdp: 1.2, approval: 3 } },
        failure: { self: { approval: -2, influence: -1 } },
      } }),
  q('cut-the-fleet', 'Retire a Fleet', 'military',
    'Sell the hulls nobody has crewed in three years. The admirals will write to the papers.',
    { situational: ['debt', 'peace', 'maritime'], cost: { pctGdp: 0 }, risk: 'medium',
      effects: {
        success: { self: { treasuryPctGdp: 1.2, military: -3, approval: -2 } },
        failure: { self: { military: -4, approval: -5, readiness: -2 } },
      } }),
  q('tourism-campaign', 'Global Tourism Campaign', 'economy',
    'Buy the airport advertising in six capitals and hope nothing explodes for a year.',
    { situational: ['peaceful', 'calm', 'stagnant'], cost: { pctGdp: 0.2 },
      skills: [['influence', 0.12]],
      effects: {
        success: { modifier: { label: 'Tourism boom', turns: 6, growth: 0.16 }, self: { influence: 2 } },
        failure: { self: { treasuryPctGdp: -0.1 } },
      } }),
  q('port-expansion', 'Deepen the Main Port', 'economy',
    'Dredge it, widen it, and take the container traffic off the neighbours.',
    { situational: ['maritime', 'exporter', 'growing'], cost: { pctGdp: 0.6 }, pc: 2,
      skills: [['tech', 0.1]],
      effects: {
        success: { modifier: { label: 'Port capacity', turns: 10, growth: 0.2 }, self: { influence: 1 } },
        failure: { self: { treasuryPctGdp: -0.3 } },
      } }),
  q('mineral-auction', 'Auction the Mineral Concessions', 'economy',
    'Sell the licences now and the royalties for thirty years. One of those is your problem.',
    { situational: ['resource', 'tight', 'debt'], cost: { pctGdp: 0 }, risk: 'medium',
      skills: [['influence', 0.1]],
      effects: {
        success: { self: { treasuryPctGdp: 1.9, influence: -1 } },
        failure: { self: { approval: -5, unrest: 3 } },
      } }),

  // ── The front ─────────────────────────────────────────────────────────────
  q('night-raids', 'Authorise Deep Raids', 'war',
    'Small teams, far behind the line, against things that are expensive to replace.',
    { situational: ['war'], requiresWar: true, target: 'nation', cost: { pctGdp: 0.35 },
      baseSuccess: 0.66, risk: 'medium', skills: [['readiness', 0.18], ['tech', 0.12]],
      warEffect: { warScore: 7, enemyExhaustion: 5, casualties: 6000 },
      warEffectOnFailure: { warScore: -3, ownExhaustion: 4, casualties: 11000 },
      effects: {
        success: { self: { approval: 3 } },
        failure: { self: { approval: -4, readiness: -3 } },
      } }),
  q('evacuate-civilians', 'Evacuate the Border Districts', 'war',
    'Move a quarter of a million people west before the front reaches them.',
    { situational: ['warLosing', 'occupied'], requiresWar: true, cost: { pctGdp: 0.4 },
      skills: [['stability', 0.14]],
      effects: {
        success: { self: { unrest: -4, approval: 5, stability: 2 } },
        failure: { self: { unrest: 7, approval: -6 } },
      } }),
  q('scorched-earth', 'Deny What You Cannot Hold', 'war',
    'Burn the depots, blow the bridges, poison the wells. It is legal, and it is not forgiven.',
    { situational: ['warLosing', 'occupied'], requiresWar: true, target: 'nation',
      cost: { pctGdp: 0.3 }, pc: 2, risk: 'high', confirm: true,
      skills: [['readiness', 0.14]],
      warEffect: { warScore: 8, enemyExhaustion: 9, casualties: 14000 },
      effects: {
        success: { self: { gdpPct: -0.5, approval: -3, influence: -3 }, worldTension: 4 },
        failure: { self: { gdpPct: -0.8, approval: -8, influence: -5 }, worldTension: 5 },
      } }),
  q('prisoner-exchange', 'Negotiate a Prisoner Exchange', 'war',
    'All for all. It is the one thing two governments at war can still agree on.',
    { situational: ['war', 'casualties'], requiresWar: true, target: 'nation',
      cost: { pctGdp: 0.04 }, baseSuccess: 0.7, skills: [['influence', 0.18]],
      effects: {
        success: { self: { approval: 8, unrest: -4 }, relation: 8, worldTension: -3 },
        failure: { self: { approval: -3 }, relation: -3 },
      } }),
  q('war-bonds', 'Issue War Bonds', 'war',
    'Ask the country to fund the thing it says it supports. The take-up is the real poll.',
    { situational: ['war', 'tight'], requiresWar: true, cost: { pctGdp: 0 }, pc: 2,
      baseSuccess: 0.72, skills: [['approval', 0.2]],
      effects: {
        success: { self: { treasuryPctGdp: 1.8, approval: 3 } },
        failure: { self: { treasuryPctGdp: 0.3, approval: -6 } },
      } }),
  q('field-hospitals', 'Stand Up the Field Hospitals', 'war',
    'Triage forward, evacuation by air. It halves the deaths and doubles the wounded.',
    { situational: ['war', 'casualties'], requiresWar: true, cost: { pctGdp: 0.25 },
      skills: [['tech', 0.14]],
      effects: {
        success: { self: { approval: 5, unrest: -3, readiness: 2 } },
        failure: { self: { approval: -3, unrest: 3 } },
      } }),
  q('rotate-the-front', 'Rotate the Front-Line Units', 'war',
    'Pull the ones who have been there since the start. Everything they know goes with them.',
    { situational: ['warExhausted'], requiresWar: true, cost: { pctGdp: 0.3 },
      skills: [['readiness', 0.16]],
      warEffect: { warScore: -2, ownExhaustion: -12, casualties: 3000 },
      effects: {
        success: { self: { readiness: 5, unrest: -3, approval: 3 } },
        failure: { self: { readiness: -2, unrest: 2 } },
      } }),
  q('court-martial', 'Court-Martial the Commander', 'war',
    'Someone lost the salient. Make it public, and hope the replacement is better.',
    { situational: ['warLosing'], requiresWar: true, cost: { pctGdp: 0.02 }, risk: 'medium',
      skills: [['stability', 0.12]],
      effects: {
        success: { self: { approval: 4, readiness: 3, stability: -1 } },
        failure: { self: { approval: -4, readiness: -5, stability: -4 } },
      } }),
  q('civil-defence', 'Civil Defence Mobilisation', 'war',
    'Shelters, sirens, drills in every school. It is grim, and it is what people want to see.',
    { situational: ['war', 'brink', 'nuclearUsed'], cost: { pctGdp: 0.2 },
      skills: [['stability', 0.14]],
      effects: {
        success: { self: { stability: 4, unrest: -3, approval: 3 } },
        failure: { self: { unrest: 5, approval: -3 } },
      } }),
  q('arm-the-partisans', 'Arm the Resistance', 'war',
    'Somebody in the occupied districts is still fighting. Give them what they need.',
    { situational: ['occupied'], requiresWar: true, target: 'nation',
      cost: { pctGdp: 0.25 }, baseSuccess: 0.64, risk: 'medium', covert: true,
      skills: [['tech', 0.1], ['influence', 0.08]],
      warEffect: { warScore: 6, enemyExhaustion: 7, casualties: 5000 },
      effects: {
        success: { self: { approval: 4 }, relation: -12 },
        failure: { self: { approval: -3, influence: -2 }, relation: -8, worldTension: 3 },
      } }),
  q('humanitarian-corridor', 'Open a Humanitarian Corridor', 'war',
    'Six hours a day, one road, watched by everyone. It is worth more abroad than at home.',
    { situational: ['occupier', 'casualties'], requiresWar: true, target: 'nation',
      cost: { pctGdp: 0.12 }, skills: [['influence', 0.16]],
      effects: {
        success: { self: { influence: 5, approval: -1 }, relation: 10, worldTension: -4 },
        failure: { self: { influence: -2 }, relation: -4 },
      } }),
  q('garrison-the-gains', 'Garrison the Occupied Districts', 'war',
    'Hold what you took with troops who will not be at the front. It is the cost of keeping it.',
    { situational: ['occupier'], requiresWar: true, cost: { pctGdp: 0.4 },
      skills: [['readiness', 0.12], ['stability', 0.1]],
      effects: {
        success: { self: { stability: 2, readiness: -3 }, modifier: { label: 'Garrison duty', turns: 6, growth: -0.08 } },
        failure: { self: { unrest: 5, readiness: -5 }, modifier: { label: 'Garrison duty', turns: 6, growth: -0.16 } },
      } }),
  q('parade-the-victory', 'Hold the Victory Parade', 'war',
    'Tanks down the main avenue while it is still true. Nothing buys a quarter like it.',
    { situational: ['warWinning'], requiresWar: true, cost: { pctGdp: 0.06 },
      skills: [['approval', 0.14]],
      effects: {
        success: { self: { approval: 9, unrest: -4, stability: 2 }, worldTension: 2 },
        failure: { self: { approval: -4, unrest: 3 } },
      } }),
  q('quiet-ceasefire', 'Sound Out a Ceasefire', 'war',
    'Not a peace. A pause, deniable, through a third country that owes you nothing.',
    { situational: ['warStalled', 'warExhausted'], requiresWar: true, target: 'nation',
      cost: { pctGdp: 0.03 }, baseSuccess: 0.6, skills: [['influence', 0.22]],
      warEffect: { warScore: 0, ownExhaustion: -8, enemyExhaustion: -6, casualties: 0 },
      effects: {
        success: { relation: 14, worldTension: -6, self: { unrest: -3 } },
        failure: { relation: -5, self: { approval: -4 } },
      } }),
  q('conscript-industry', 'Direct the Factories', 'war',
    'Tell the car plants what they are making now. It works, and they never fully go back.',
    { situational: ['war', 'exporter'], requiresWar: true, cost: { pctGdp: 0.5 }, pc: 2,
      skills: [['tech', 0.14], ['stability', 0.1]],
      effects: {
        success: { self: { military: 4, readiness: 4 }, modifier: { label: 'Directed industry', turns: 6, growth: -0.2 } },
        failure: { self: { readiness: 1, unrest: 4 }, modifier: { label: 'Directed industry', turns: 5, growth: -0.32 } },
      } }),

  // ── Abroad ────────────────────────────────────────────────────────────────
  q('emergency-summit', 'Convene an Emergency Summit', 'diplomacy',
    'Get them in a room this week. Half the value is that you were the one who called it.',
    { situational: ['tension', 'escalation', 'brink'], cost: { pctGdp: 0.08 }, pc: 2,
      baseSuccess: 0.68, skills: [['influence', 0.24]],
      effects: {
        success: { self: { influence: 6 }, worldTension: -8 },
        failure: { self: { influence: -3, approval: -2 } },
      } }),
  q('offer-mediation', 'Offer to Mediate', 'diplomacy',
    'Somebody else\'s war, your hotel, your foreign minister in every photograph.',
    { situational: ['warNextDoor', 'peace'], cost: { pctGdp: 0.06 }, baseSuccess: 0.62,
      skills: [['influence', 0.24]],
      effects: {
        success: { self: { influence: 7, approval: 2 }, worldTension: -5 },
        failure: { self: { influence: -3 } },
      } }),
  q('recognise-government', 'Recognise the New Government', 'diplomacy',
    'Somebody took power next door by force. Deciding quickly is itself the decision.',
    { situational: ['coup', 'neighbourCrisis'], target: 'nation', cost: { pctGdp: 0.02 },
      pc: 2, risk: 'medium', skills: [['influence', 0.16]],
      effects: {
        success: { relation: 26, self: { influence: 3 }, worldTension: 2 },
        failure: { relation: 6, self: { influence: -4, approval: -3 } },
      } }),
  q('expel-diplomats', 'Expel the Diplomatic Staff', 'diplomacy',
    'Forty-eight hours, whole mission. It says one thing and it says it very clearly.',
    { situational: ['escalation', 'hostileNeighbour', 'cyber'], target: 'nation',
      cost: { pctGdp: 0.01 }, skills: [],
      effects: {
        success: { relation: -14, self: { approval: 4 }, worldTension: 3 },
        failure: { relation: -10, self: { influence: -2 } },
      } }),
  q('make-the-state-visit', 'Make the State Visit', 'diplomacy',
    'Three days, a banquet, and one signature that was agreed six months ago.',
    { situational: ['peaceful', 'influential', 'isolated'], target: 'nation',
      cost: { pctGdp: 0.09 }, skills: [['influence', 0.2]],
      effects: {
        success: { relation: 16, self: { influence: 3, approval: 2 } },
        failure: { relation: 2, self: { approval: -3 } },
      } }),
  q('send-aid', 'Send an Aid Package', 'diplomacy',
    'Money and matériel to somebody having a worse quarter than you.',
    { situational: ['warNextDoor', 'neighbourCrisis', 'rich'], target: 'nation',
      cost: { pctGdp: 0.4 }, skills: [['influence', 0.16]],
      effects: {
        success: { relation: 22, self: { influence: 5 } },
        failure: { relation: 8, self: { influence: 1, approval: -3 } },
      } }),
  q('un-resolution', 'Table a Resolution', 'diplomacy',
    'It will be vetoed. The vote is the point, not the outcome.',
    { situational: ['tension', 'conquest', 'nuclearUsed'], target: 'nation',
      cost: { pctGdp: 0.03 }, baseSuccess: 0.64, skills: [['influence', 0.22]],
      effects: {
        success: { relation: -10, self: { influence: 5, approval: 3 }, worldTension: 2 },
        failure: { relation: -6, self: { influence: -3 } },
      } }),
  q('visa-liberalisation', 'Open the Visas', 'diplomacy',
    'Let them come without asking first. Nothing else buys goodwill this cheaply.',
    { situational: ['isolated', 'peaceful'], target: 'nation', cost: { pctGdp: 0.05 },
      skills: [['influence', 0.14]],
      effects: {
        success: { relation: 18, self: { influence: 2 }, modifier: { label: 'Open borders', turns: 6, growth: 0.08 } },
        failure: { relation: 4, self: { unrest: 3, approval: -3 } },
      } }),
  q('join-the-bloc', 'Apply for Membership', 'diplomacy',
    'Start the paperwork publicly. It commits you before the negotiation begins.',
    { situational: ['isolated', 'hostileNeighbour'], cost: { pctGdp: 0.1 }, pc: 2,
      baseSuccess: 0.6, skills: [['influence', 0.24], ['stability', 0.1]],
      effects: {
        success: { self: { influence: 8, approval: 4 }, worldTension: 3 },
        failure: { self: { influence: -3, approval: -5 } },
      } }),
  q('neutrality-declaration', 'Declare Formal Neutrality', 'diplomacy',
    'Announce that you are in nobody\'s camp. Both camps will find that suspicious.',
    { situational: ['tension', 'warNextDoor', 'weakArmy'], cost: { pctGdp: 0.05 }, pc: 2,
      risk: 'medium', skills: [['influence', 0.16]],
      effects: {
        success: { self: { influence: 2, approval: 5, stability: 3 }, worldTension: -3 },
        failure: { self: { influence: -5, approval: -3 } },
      } }),
  q('host-the-talks', 'Host the Talks', 'diplomacy',
    'A neutral city, a long table, and your flag behind both delegations.',
    { situational: ['tension', 'warNextDoor', 'influential'], cost: { pctGdp: 0.12 },
      baseSuccess: 0.66, skills: [['influence', 0.22]],
      effects: {
        success: { self: { influence: 7, approval: 3 }, worldTension: -6 },
        failure: { self: { influence: -2 } },
      } }),
  q('recall-for-consultation', 'Recall for Consultations', 'diplomacy',
    'Not an expulsion. Everyone knows exactly how much less it is than one.',
    { situational: ['escalation', 'hostileNeighbour'], target: 'nation', cost: { pctGdp: 0.01 },
      effects: {
        success: { relation: -6, self: { approval: 2 }, worldTension: 1 },
        failure: { relation: -4, self: { influence: -1 } },
      } }),
  q('congratulate-quietly', 'Send Quiet Congratulations', 'diplomacy',
    'No press release. A letter, delivered by hand, to somebody who will remember it.',
    { situational: ['coup', 'newState'], target: 'nation', cost: { pctGdp: 0.01 },
      baseSuccess: 0.82, skills: [['influence', 0.12]],
      effects: {
        success: { relation: 14, self: { influence: 1 } },
        failure: { relation: 2, self: { influence: -2, approval: -2 } },
      } }),
  q('sanctions-relief', 'Ease the Sanctions', 'diplomacy',
    'Lift the ones that were hurting the wrong people. Claim credit for the rest.',
    { situational: ['peaceful', 'influential'], target: 'nation', cost: { pctGdp: 0.02 },
      skills: [['influence', 0.16]],
      effects: {
        success: { relation: 24, self: { influence: 3, approval: -2 }, worldTension: -4 },
        failure: { relation: 8, self: { approval: -5 } },
      } }),
  q('defence-guarantee', 'Extend a Security Guarantee', 'diplomacy',
    'Put your name on somebody else\'s border. It is the most expensive sentence in diplomacy.',
    { situational: ['strongArmy', 'warNextDoor', 'influential'], target: 'nation',
      cost: { pctGdp: 0.2 }, pc: 3, risk: 'medium', skills: [['influence', 0.2], ['military', 0.12]],
      effects: {
        success: { relation: 34, self: { influence: 7 }, worldTension: 5 },
        failure: { relation: 10, self: { influence: -4, readiness: -3 }, worldTension: 6 },
      } }),

  // ── The quiet services ────────────────────────────────────────────────────
  q('plug-the-leak', 'Find the Leak', 'intelligence',
    'Somebody in the building is talking. Narrow it to a floor, then to a desk.',
    { situational: ['cyber', 'fragile', 'escalation'], cost: { pctGdp: 0.08 },
      baseSuccess: 0.66, skills: [['tech', 0.16]],
      effects: {
        success: { self: { stability: 4, influence: 2 } },
        failure: { self: { stability: -3, unrest: 2, approval: -2 } },
      } }),
  q('harden-the-grid', 'Harden the Grid', 'intelligence',
    'Air-gap what can be air-gapped and accept how much cannot.',
    { situational: ['cyber', 'accident', 'techLead'], cost: { pctGdp: 0.3 },
      skills: [['tech', 0.2]],
      effects: {
        success: { self: { stability: 3, tech: 1 }, modifier: { label: 'Hardened infrastructure', turns: 8, growth: 0.06 } },
        failure: { self: { treasuryPctGdp: -0.2 } },
      } }),
  q('turn-an-asset', 'Turn Somebody', 'intelligence',
    'One official, one grievance, one very long conversation.',
    { situational: ['escalation', 'hostileNeighbour'], target: 'nation', covert: true,
      cost: { pctGdp: 0.12 }, baseSuccess: 0.55, risk: 'medium', skills: [['tech', 0.14]],
      effects: {
        success: { self: { tech: 2, influence: 2 }, relation: -4 },
        failure: { self: { influence: -3 }, relation: -14, worldTension: 3 },
      } }),
  q('counter-disinfo', 'Counter-Disinformation Unit', 'intelligence',
    'Stand up a team whose whole job is the version of events being read at home.',
    { situational: ['unrest', 'cyber', 'unpopular'], cost: { pctGdp: 0.15 },
      skills: [['tech', 0.12], ['influence', 0.08]],
      effects: {
        success: { self: { unrest: -5, stability: 3, approval: 3 } },
        failure: { self: { approval: -4, unrest: 3 } },
      } }),
  q('buy-the-satellite-time', 'Buy Commercial Satellite Time', 'intelligence',
    'You do not need your own constellation to know what moved last night.',
    { situational: ['war', 'escalation', 'techLag'], cost: { pctGdp: 0.18 },
      skills: [['tech', 0.14]],
      effects: {
        success: { self: { readiness: 4, tech: 1 } },
        failure: { self: { treasuryPctGdp: -0.1 } },
      } }),
  q('publish-the-intercepts', 'Publish the Intercepts', 'intelligence',
    'Burn the source to win the argument. Sometimes the argument is worth more.',
    { situational: ['escalation', 'attack', 'brink'], target: 'nation', cost: { pctGdp: 0.02 },
      pc: 2, risk: 'medium', skills: [['influence', 0.16], ['tech', 0.1]],
      effects: {
        success: { self: { influence: 6, approval: 4 }, relation: -18, worldTension: 4 },
        failure: { self: { influence: -5, approval: -3 }, relation: -10, worldTension: 5 },
      } }),
  q('vet-the-officers', 'Vet the Officer Corps', 'intelligence',
    'Read every file above colonel. You will find something, and finding it costs you.',
    { situational: ['coup', 'fragile'], cost: { pctGdp: 0.1 }, pc: 2, risk: 'medium',
      skills: [['stability', 0.16]],
      effects: {
        success: { self: { stability: 7, readiness: -3 } },
        failure: { self: { stability: -5, readiness: -6, unrest: 4 } },
      } }),
  q('trace-the-money', 'Trace the Financing', 'intelligence',
    'Follow it through four jurisdictions and publish the fifth.',
    { situational: ['attack', 'unrest'], cost: { pctGdp: 0.1 }, baseSuccess: 0.62,
      skills: [['tech', 0.16], ['influence', 0.08]],
      effects: {
        success: { self: { stability: 4, influence: 3, unrest: -3 } },
        failure: { self: { approval: -3 } },
      } }),
  q('safe-passage', 'Offer Safe Passage', 'intelligence',
    'Let the ones who lost leave quietly. It is cheaper than what they would do if they stayed.',
    { situational: ['coup', 'fragile'], cost: { pctGdp: 0.03 }, risk: 'medium',
      skills: [['influence', 0.12]],
      effects: {
        success: { self: { stability: 5, unrest: -4, approval: -2 } },
        failure: { self: { stability: -3, approval: -5 } },
      } }),
  q('close-the-embassy', 'Close a Station', 'intelligence',
    'Shut the residency before the host service does it for you, loudly.',
    { situational: ['escalation', 'sanctioned'], target: 'nation', cost: { pctGdp: 0.02 },
      effects: {
        success: { self: { stability: 2 }, relation: -8 },
        failure: { self: { influence: -3 }, relation: -12, worldTension: 2 },
      } }),

  // ── Laboratories and factories ────────────────────────────────────────────
  q('poach-the-researchers', 'Poach the Researchers', 'technology',
    'Three labs, forty people, whatever it costs. The papers follow the people.',
    { situational: ['techLag', 'rich'], target: 'nation', cost: { pctGdp: 0.3 },
      baseSuccess: 0.68, skills: [['tech', 0.16], ['influence', 0.08]],
      effects: {
        success: { self: { tech: 3 }, relation: -8 },
        failure: { self: { treasuryPctGdp: -0.2, influence: -1 } },
      } }),
  q('open-source-mandate', 'Mandate Open Standards', 'technology',
    'Break one vendor\'s grip on the whole state. It saves money for a decade.',
    { situational: ['techLag', 'debt'], cost: { pctGdp: 0.12 }, pc: 2,
      skills: [['tech', 0.18]],
      effects: {
        success: { self: { tech: 2 }, modifier: { label: 'Open standards', turns: 8, growth: 0.1 } },
        failure: { self: { tech: -1, treasuryPctGdp: -0.1 } },
      } }),
  q('national-lab', 'Fund a National Laboratory', 'technology',
    'One building, one problem, twenty years. Your successor cuts the ribbon.',
    { situational: ['techLead', 'rich', 'growing'], cost: { pctGdp: 0.55 }, pc: 2,
      skills: [['tech', 0.2]],
      effects: {
        success: { self: { tech: 3 }, modifier: { label: 'Research base', turns: 12, growth: 0.14 } },
        failure: { self: { treasuryPctGdp: -0.3 } },
      } }),
  q('chip-stockpile', 'Stockpile the Critical Components', 'technology',
    'Buy two years of the things you cannot make. It is not a strategy; it is time.',
    { situational: ['techLag', 'tension', 'sanctioned'], cost: { pctGdp: 0.4 },
      skills: [['tech', 0.12]],
      effects: {
        success: { self: { tech: 1 }, modifier: { label: 'Component reserve', turns: 8, growth: 0.08 } },
        failure: { self: { treasuryPctGdp: -0.3 } },
      } }),
  q('grid-storage', 'Build Out Grid Storage', 'technology',
    'The generation was never the hard part.',
    { situational: ['accident', 'energy', 'techLead'], cost: { pctGdp: 0.5 }, pc: 2,
      skills: [['tech', 0.16]],
      effects: {
        success: { self: { tech: 2 }, modifier: { label: 'Grid resilience', turns: 10, growth: 0.16 } },
        failure: { self: { treasuryPctGdp: -0.3 } },
      } }),
  q('reactor-restart', 'Restart the Reactors', 'technology',
    'The ones that were shut down for reasons nobody now remembers as clearly.',
    { situational: ['energy', 'accident', 'commodityShock'], cost: { pctGdp: 0.45 },
      pc: 2, risk: 'medium', skills: [['tech', 0.2], ['stability', 0.08]],
      effects: {
        success: { self: { tech: 1, unrest: 3 }, modifier: { label: 'Baseload restored', turns: 10, growth: 0.2 } },
        failure: { self: { unrest: 8, approval: -6 } },
      } }),
  q('undersea-cable', 'Lay a New Cable', 'technology',
    'One more route to the rest of the world that does not run through a rival.',
    { situational: ['maritime', 'isolated', 'techLead'], cost: { pctGdp: 0.35 },
      skills: [['tech', 0.14]],
      effects: {
        success: { self: { tech: 2, influence: 2 }, modifier: { label: 'Connectivity', turns: 8, growth: 0.1 } },
        failure: { self: { treasuryPctGdp: -0.2 } },
      } }),
  q('vaccine-plant', 'Build a Vaccine Plant', 'technology',
    'So the next time, you are not ninth in the queue.',
    { situational: ['epidemic', 'techLag'], cost: { pctGdp: 0.4 }, pc: 2,
      skills: [['tech', 0.16]],
      effects: {
        success: { self: { tech: 2, approval: 4 }, modifier: { label: 'Health capacity', turns: 10, growth: 0.06 } },
        failure: { self: { treasuryPctGdp: -0.3, approval: -2 } },
      } }),
  q('desalination', 'Commission Desalination', 'technology',
    'Expensive water beats no water, and the argument ends there.',
    { situational: ['disaster', 'famine', 'agrarian'], cost: { pctGdp: 0.5 },
      skills: [['tech', 0.14]],
      effects: {
        success: { self: { unrest: -5 }, modifier: { label: 'Water security', turns: 10, growth: 0.1 } },
        failure: { self: { treasuryPctGdp: -0.3, approval: -2 } },
      } }),
  q('launch-window', 'Buy a Launch Window', 'technology',
    'Somebody else\'s rocket, your satellite, your flag on the fairing.',
    { situational: ['techLead', 'influential'], cost: { pctGdp: 0.25 },
      skills: [['tech', 0.18]],
      effects: {
        success: { self: { tech: 2, influence: 4, approval: 3 } },
        failure: { self: { treasuryPctGdp: -0.2, approval: -3 } },
      } }),

  // ── Weather, illness and accident ─────────────────────────────────────────
  q('airlift', 'Order the Airlift', 'domestic',
    'Every transport aircraft you have, flying to one province, starting tonight.',
    { situational: ['disaster', 'famine'], cost: { pctGdp: 0.35 },
      skills: [['readiness', 0.14]],
      effects: {
        success: { self: { approval: 8, unrest: -6, readiness: -2 } },
        failure: { self: { approval: -6, unrest: 4 } },
      } }),
  q('accept-foreign-aid', 'Accept the Foreign Assistance', 'diplomacy',
    'Say yes to the help. It is an admission, and it saves people.',
    { situational: ['disaster', 'epidemic', 'famine'], cost: { pctGdp: 0 },
      skills: [['influence', 0.1]],
      effects: {
        success: { self: { unrest: -6, approval: 2, influence: -2 } },
        failure: { self: { approval: -5, influence: -3 } },
      } }),
  q('quarantine-province', 'Quarantine the Province', 'domestic',
    'Ring the affected districts. It works, and it makes enemies of everyone inside.',
    { situational: ['epidemic'], cost: { pctGdp: 0.25 }, risk: 'medium',
      skills: [['stability', 0.14], ['tech', 0.1]],
      effects: {
        success: { self: { unrest: 3, stability: 3 }, modifier: { label: 'Contained outbreak', turns: 3, growth: -0.08 } },
        failure: { self: { unrest: 9, approval: -6 }, modifier: { label: 'Uncontrolled outbreak', turns: 5, growth: -0.3, unrest: 1 } },
      } }),
  q('mass-vaccination', 'Mass Vaccination Drive', 'domestic',
    'Everything you have, in arms, in eight weeks.',
    { situational: ['epidemic'], cost: { pctGdp: 0.4 }, skills: [['tech', 0.16]],
      effects: {
        success: { self: { approval: 7, unrest: -6 } },
        failure: { self: { approval: -5, unrest: 4 } },
      } }),
  q('rebuild-programme', 'Announce the Reconstruction', 'economy',
    'A number, a date, and a minister whose only job is this.',
    { situational: ['disaster', 'accident'], cost: { pctGdp: 0.6 }, pc: 2,
      skills: [['stability', 0.12]],
      effects: {
        success: { self: { approval: 6, unrest: -4 }, modifier: { label: 'Reconstruction', turns: 8, growth: 0.18 } },
        failure: { self: { approval: -5, treasuryPctGdp: -0.3 } },
      } }),
  q('safety-review', 'Order a National Safety Review', 'domestic',
    'Every plant, every dam, every bridge. You will not like the total.',
    { situational: ['accident'], cost: { pctGdp: 0.2 }, skills: [['tech', 0.14]],
      effects: {
        success: { self: { stability: 4, approval: 4 }, modifier: { label: 'Safety programme', turns: 6, growth: -0.06 } },
        failure: { self: { approval: -4, unrest: 3 } },
      } }),
  q('compensate-the-families', 'Compensate the Families', 'domestic',
    'Pay it now, pay it publicly, and do not make them ask twice.',
    { situational: ['accident', 'disaster', 'attack'], cost: { pctGdp: 0.15 },
      effects: {
        success: { self: { approval: 6, unrest: -5 } },
        failure: { self: { approval: -6, unrest: 5 } },
      } }),
  q('refugee-camps', 'Open Reception Centres', 'domestic',
    'They are coming whatever you announce. Better organised than not.',
    { situational: ['refugees', 'warNextDoor'], cost: { pctGdp: 0.3 }, risk: 'medium',
      skills: [['stability', 0.12], ['influence', 0.08]],
      effects: {
        success: { self: { influence: 5, unrest: 3, approval: -2 } },
        failure: { self: { unrest: 8, approval: -7, influence: 1 } },
      } }),
  q('firebreaks', 'Cut the Firebreaks', 'domestic',
    'Bulldoze the corridors before the season, not during it.',
    { situational: ['disaster', 'agrarian'], cost: { pctGdp: 0.15 },
      effects: {
        success: { self: { stability: 2 }, modifier: { label: 'Disaster preparation', turns: 8, growth: 0.04 } },
        failure: { self: { treasuryPctGdp: -0.1 } },
      } }),
  q('flood-defences', 'Raise the Flood Defences', 'domestic',
    'A metre of concrete that will be either invisible or the only thing anyone remembers.',
    { situational: ['disaster', 'maritime'], cost: { pctGdp: 0.45 }, pc: 2,
      skills: [['tech', 0.12]],
      effects: {
        success: { self: { approval: 3 }, modifier: { label: 'Flood defences', turns: 12, growth: 0.06 } },
        failure: { self: { treasuryPctGdp: -0.3, approval: -2 } },
      } }),

  // ── Ground, borders and new flags ─────────────────────────────────────────
  q('fortify-the-border', 'Fortify the Frontier', 'military',
    'Ditches, mines, sensors, and a line on the map that is now a line on the ground.',
    { situational: ['hostileNeighbour', 'warNextDoor', 'borderChange'], cost: { pctGdp: 0.4 },
      skills: [['readiness', 0.14]],
      effects: {
        success: { self: { readiness: 5, stability: 2 }, worldTension: 2 },
        failure: { self: { treasuryPctGdp: -0.3, readiness: 1 } },
      } }),
  q('buy-the-province', 'Open Talks to Buy the Province', 'diplomacy',
    'It has been done before. It is cheaper than the alternative and nobody ever forgets it.',
    { situational: ['rich', 'borderChange', 'peace'], target: 'nation',
      cost: { pctGdp: 1.4 }, pc: 3, baseSuccess: 0.45, risk: 'medium', confirm: true,
      skills: [['influence', 0.24]],
      effects: {
        success: { relation: 12, self: { influence: 3, approval: 2 }, worldTension: 4 },
        failure: { relation: -14, self: { influence: -4, approval: -4 }, worldTension: 3 },
      } }),
  q('resettle-the-frontier', 'Resettle the Frontier Districts', 'domestic',
    'Move people into ground you have just taken. It is how a border becomes permanent.',
    { situational: ['occupier', 'borderChange'], cost: { pctGdp: 0.4 }, pc: 2, risk: 'medium',
      skills: [['stability', 0.12]],
      effects: {
        success: { self: { stability: 3, unrest: 3, influence: -3 }, worldTension: 4 },
        failure: { self: { unrest: 8, approval: -5, influence: -5 }, worldTension: 5 },
      } }),
  q('autonomy-offer', 'Offer the Region Autonomy', 'domestic',
    'Give it its own parliament before it declares one.',
    { situational: ['newState', 'fragile', 'unrest'], cost: { pctGdp: 0.2 }, pc: 3,
      risk: 'medium', skills: [['stability', 0.16], ['influence', 0.08]],
      effects: {
        success: { self: { stability: 8, unrest: -10, approval: -3 } },
        failure: { self: { stability: -6, unrest: 6, approval: -7 } },
      } }),
  q('census', 'Order a National Census', 'domestic',
    'Find out who actually lives where. Every answer is politically inconvenient to somebody.',
    { situational: ['borderChange', 'refugees', 'newState'], cost: { pctGdp: 0.12 },
      skills: [['tech', 0.1], ['stability', 0.08]],
      effects: {
        success: { self: { stability: 3, tech: 1 }, modifier: { label: 'Better administration', turns: 8, growth: 0.08 } },
        failure: { self: { unrest: 4, approval: -3 } },
      } }),
  q('border-market', 'Open a Border Market', 'economy',
    'Let the two sides trade in daylight instead of at night for twice the price.',
    { situational: ['hostileNeighbour', 'peace', 'borderChange'], target: 'nation',
      cost: { pctGdp: 0.08 }, skills: [['influence', 0.14]],
      effects: {
        success: { relation: 14, modifier: { label: 'Border trade', turns: 6, growth: 0.1 } },
        failure: { relation: 2, self: { unrest: 2 } },
      } }),
  q('demilitarised-zone', 'Propose a Demilitarised Zone', 'diplomacy',
    'Ten kilometres either side, monitored by somebody neither of you controls.',
    { situational: ['escalation', 'hostileNeighbour', 'warStalled'], target: 'nation',
      cost: { pctGdp: 0.1 }, pc: 2, baseSuccess: 0.6, skills: [['influence', 0.22]],
      effects: {
        success: { relation: 22, worldTension: -7, self: { influence: 4, readiness: -2 } },
        failure: { relation: -4, self: { approval: -3 } },
      } }),
  q('name-the-territory', 'Rename the Acquired Territory', 'domestic',
    'New signage, new maps, new textbooks. Trivial, and the argument lasts a century.',
    { situational: ['occupier', 'conquest'], cost: { pctGdp: 0.03 }, risk: 'medium',
      effects: {
        success: { self: { approval: 5, stability: 2, influence: -3 }, worldTension: 3 },
        failure: { self: { approval: -3, unrest: 4, influence: -4 }, worldTension: 3 },
      } }),
  q('recognise-independence', 'Recognise the Secession', 'diplomacy',
    'Accept the thing that already happened, and get the credit for accepting it.',
    { situational: ['newState'], target: 'nation', cost: { pctGdp: 0.02 }, pc: 2,
      risk: 'medium', skills: [['influence', 0.16]],
      effects: {
        success: { relation: 34, self: { influence: 4 }, worldTension: 3 },
        failure: { relation: 10, self: { influence: -3, approval: -4 } },
      } }),
  q('coastal-claim', 'File the Continental Shelf Claim', 'diplomacy',
    'Two hundred pages of seabed survey and a claim to everything under it.',
    { situational: ['maritime', 'resource', 'energy'], cost: { pctGdp: 0.15 },
      baseSuccess: 0.6, skills: [['tech', 0.14], ['influence', 0.12]],
      effects: {
        success: { self: { influence: 4 }, modifier: { label: 'Offshore rights', turns: 12, growth: 0.12 }, worldTension: 2 },
        failure: { self: { influence: -2 }, worldTension: 3 },
      } }),

  // ── When the world is looking at you ──────────────────────────────────────
  q('open-the-inspectors', 'Invite the Inspectors', 'diplomacy',
    'Let them see it. It is the only way to end an argument about what you have.',
    { situational: ['pariah', 'sanctioned', 'nuclear'], cost: { pctGdp: 0.06 }, pc: 2,
      skills: [['influence', 0.18]],
      effects: {
        success: { self: { influence: 7, approval: -3 }, worldTension: -8 },
        failure: { self: { influence: -4, approval: -5 }, worldTension: 2 },
      } }),
  q('unilateral-drawdown', 'Announce a Unilateral Drawdown', 'military',
    'Pull back from somebody\'s border without being asked. It is read as either strength or fear.',
    { situational: ['feared', 'pariah', 'tension'], cost: { pctGdp: 0 }, pc: 2,
      risk: 'medium', skills: [['influence', 0.18]],
      effects: {
        success: { self: { influence: 6, readiness: -3 }, worldTension: -9 },
        failure: { self: { influence: -3, approval: -5, readiness: -4 } },
      } }),
  q('reparations-fund', 'Establish a Reparations Fund', 'diplomacy',
    'Pay for what you did. It is expensive and it is the only thing that actually works.',
    { situational: ['pariah', 'conquest', 'occupier'], cost: { pctGdp: 1.1 }, pc: 3,
      skills: [['influence', 0.2]],
      effects: {
        success: { self: { influence: 9, approval: -5 }, worldTension: -6 },
        failure: { self: { influence: 1, approval: -8 } },
      } }),
  q('charm-offensive', 'Send the Delegations', 'diplomacy',
    'Twelve capitals in four weeks. Not one of them expects to be persuaded.',
    { situational: ['feared', 'isolated', 'sanctioned'], cost: { pctGdp: 0.14 },
      baseSuccess: 0.66, skills: [['influence', 0.22]],
      effects: {
        success: { self: { influence: 6, approval: 2 }, worldTension: -3 },
        failure: { self: { influence: -3, approval: -2 } },
      } }),
  q('no-first-use', 'Declare No First Use', 'military',
    'A promise about the worst thing you own. It is worth precisely what people think it is.',
    { situational: ['nuclear', 'feared', 'brink'], cost: { pctGdp: 0 }, pc: 2,
      skills: [['influence', 0.18]],
      effects: {
        success: { self: { influence: 6 }, worldTension: -10 },
        failure: { self: { influence: -2, approval: -5 }, worldTension: -2 },
      } }),

  q('pension-reform', 'Move the Pension Age', 'domestic',
    'Two more years, phased over ten. Everybody agrees it is necessary and nobody forgives it.',
    { situational: ['aging', 'debt'], cost: { pctGdp: 0 }, pc: 3, risk: 'high',
      skills: [['stability', 0.18], ['approval', 0.08]],
      effects: {
        success: { self: { treasuryPctGdp: 1.2, unrest: 7, approval: -9 }, modifier: { label: 'Pension savings', turns: 12, growth: 0.1 } },
        failure: { self: { unrest: 13, approval: -14, stability: -4 } },
      } }),
  q('commercialise-it', 'Take the Breakthrough to Market', 'technology',
    'Get it out of the laboratory and onto an export licence before somebody else does.',
    { situational: ['breakthrough', 'techLead'], cost: { pctGdp: 0.3 }, pc: 2,
      skills: [['tech', 0.2], ['influence', 0.06]],
      effects: {
        success: { self: { tech: 2, influence: 3 }, modifier: { label: 'Export licences', turns: 8, growth: 0.22 } },
        failure: { self: { treasuryPctGdp: -0.2, tech: 1 } },
      } }),
  q('constitutional-settlement', 'Put the Settlement to a Vote', 'domestic',
    'Fix the arrangement while you are strong enough that the answer is not in doubt.',
    { situational: ['solid', 'popular'], cost: { pctGdp: 0.1 }, pc: 3, risk: 'medium',
      skills: [['stability', 0.2], ['approval', 0.12]],
      effects: {
        success: { self: { stability: 9, approval: 4 }, modifier: { label: 'Constitutional settlement', turns: 14, growth: 0.06 } },
        failure: { self: { stability: -6, approval: -8, unrest: 5 } },
      } }),
];


/** Ids, for the translation test and for anything that wants the catalogue. */
export const QUICK_ORDER_IDS = QUICK_ORDERS.map((a) => a.id);
